project_id = "uzoiiijqtahohfafqirm"

[functions.dispatchHabitReminders]
verify_jwt = false

[functions.realtime-token]
verify_jwt = false

[functions.food-search]
verify_jwt = false

[functions.food-text-lookup]
verify_jwt = false

[functions.vision-ocr]
verify_jwt = true

[functions.gpt-detect-diag]
verify_jwt = false

[functions.gpt-vision-selftest]
verify_jwt = false

[functions.nv-search]
verify_jwt = true

[functions.nv-write]
verify_jwt = true