project_id = "uzoiiijqtahohfafqirm"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.log-workout-xp]
verify_jwt = true

[functions.trigger-meditation-nudge]
verify_jwt = false

[functions.trigger-breathing-nudge]
verify_jwt = false

[functions.trigger-yoga-nudge]
verify_jwt = false

[functions.trigger-sleep-nudge]
verify_jwt = false

[functions.update-yearly-scores-preview]
verify_jwt = false

[functions.activate-routine-safely]
verify_jwt = true

[functions.generateCaricatureImage]
verify_jwt = true

[functions.cleanup-unverified-accounts]
verify_jwt = true

[functions.log-voice-gpt5]
verify_jwt = true

[functions.gpt5-vision-food-detector]
verify_jwt = false

[functions.gpt5-smart-food-analyzer]
verify_jwt = false

[functions.oauth-exchange-token]
verify_jwt = true

[functions.oauth-disconnect]
verify_jwt = true

[functions.oauth-config]
verify_jwt = false