
project_id = "uzoiiijqtahohfafqirm"

[functions.generate-weekly-health-report]
verify_jwt = false

[functions.generate-monthly-reports]
verify_jwt = false

[functions.generate-yearly-reports]
verify_jwt = false

[functions.generate-and-save-weekly-health-pdf]
verify_jwt = false

[functions.assign-monthly-rankings]

[functions.generate-monthly-summary]

[functions.get-trophy-counts]

[functions.generate-weekly-summary]
verify_jwt = false

[functions.health-check-processor]
verify_jwt = false

[functions.vision-label-reader]
verify_jwt = false

[functions.ai-coach-chat]
verify_jwt = false

[functions.log-voice]
verify_jwt = false

[functions.voice-to-text]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.parse-food-items]
verify_jwt = false

[functions.barcode-lookup-global]
verify_jwt = false

[functions.detect-flagged-ingredients]
verify_jwt = false

[functions.test-function]
verify_jwt = false

[functions.detect-toxins]
verify_jwt = false

[functions.barcode-image-detector]
verify_jwt = false

[functions.evaluate-meal-quality]
verify_jwt = false

[functions.batch-evaluate-meals]
verify_jwt = false

[functions.calculate-daily-performance]
verify_jwt = false

[functions.calculate-daily-score]
verify_jwt = false

[functions.generate-monthly-exercise-reports]
verify_jwt = false

[functions.generate-yearly-exercise-reports]
verify_jwt = false

[functions.test-yearly-reports]
verify_jwt = false
