
project_id = "uzoiiijqtahohfafqirm"

[functions.vision-label-reader]
verify_jwt = false

[functions.ai-coach-chat]
verify_jwt = false

[functions.log-voice]
verify_jwt = false

[functions.voice-to-text]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.parse-food-items]
verify_jwt = false

[functions.barcode-lookup-global]
verify_jwt = false

[functions.detect-flagged-ingredients]
verify_jwt = false
