
project_id = "uzoiiijqtahohfafqirm"

[functions.generate-weekly-health-report]
verify_jwt = true

[functions.generate-monthly-reports]
verify_jwt = true

[functions.generate-yearly-reports]
verify_jwt = true

[functions.generate-and-save-weekly-health-pdf]
verify_jwt = true

[functions.assign-monthly-rankings]
verify_jwt = true

[functions.generate-monthly-summary]
verify_jwt = true

[functions.get-trophy-counts]
verify_jwt = true

[functions.generate-weekly-summary]
verify_jwt = true

[functions.health-check-processor]
verify_jwt = true

[functions.vision-label-reader]
verify_jwt = true

[functions.ai-coach-chat]
verify_jwt = true

[functions.log-voice]
verify_jwt = true

[functions.voice-to-text]
verify_jwt = true

[functions.send-push-notification]
verify_jwt = true

[functions.parse-food-items]
verify_jwt = true

[functions.barcode-lookup-global]
verify_jwt = false

[functions.detect-flagged-ingredients]
verify_jwt = true

[functions.test-function]
verify_jwt = false

[functions.detect-toxins]
verify_jwt = true

[functions.barcode-image-detector]
verify_jwt = true

[functions.evaluate-meal-quality]
verify_jwt = true

[functions.batch-evaluate-meals]
verify_jwt = true

[functions.calculate-daily-performance]
verify_jwt = true

[functions.calculate-daily-score]
verify_jwt = true

[functions.generate-monthly-exercise-reports]
verify_jwt = true

[functions.generate-yearly-exercise-reports]
verify_jwt = true

[functions.test-yearly-reports]
verify_jwt = true

[functions.analyze-mood-journal]
verify_jwt = true

[functions.analyze-weekly-exercise-progress]
verify_jwt = true

[functions.body-scan-notifications]
verify_jwt = true

[functions.calculate-daily-meal-averages]
verify_jwt = true

[functions.calculate-daily-targets]
verify_jwt = true

[functions.cleanup-unverified-accounts]
verify_jwt = true

[functions.enhanced-food-filter]
verify_jwt = true

[functions.generate-meal-suggestions]
verify_jwt = true

[functions.generate-smart-suggestions]
verify_jwt = true

[functions.match-branded-product]
verify_jwt = true

[functions.predict-mood]
verify_jwt = true

[functions.schedule-mood-notifications]
verify_jwt = true

[functions.smart-meal-nudges]
verify_jwt = true

[functions.weekly-exercise-insights-cron]
verify_jwt = true

[functions.yearly-hall-of-fame]
verify_jwt = true
