DO $$
DECLARE
  v_payload jsonb := '[
  {
    "slug": "daily-planning-5",
    "name": "Daily Planning (5 min)",
    "domain": "recovery",
    "category": "planning",
    "summary": "Clarify top 1–3 priorities and reduce decision fatigue.",
    "goal_type": "duration",
    "default_target": 5.0,
    "min_viable": "Write one top task.",
    "time_windows": [{ "start": "07:00", "end": "10:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Pair with morning coffee.",
    "equipment": "notebook",
    "contraindications": "",
    "difficulty": "easy",
    "estimated_minutes": 5,
    "coach_copy": null,
    "tags": "planning,focus,priorities",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "pomodoro-25",
    "name": "Pomodoro Work Block (25 min)",
    "domain": "recovery",
    "category": "focus",
    "summary": "Single-tasking to improve deep work.",
    "goal_type": "duration",
    "default_target": 25.0,
    "min_viable": "Do 10 minutes distraction-free.",
    "time_windows": [{ "start": "09:00", "end": "17:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Start of work session.",
    "equipment": "timer",
    "contraindications": "",
    "difficulty": "easy",
    "estimated_minutes": 25,
    "coach_copy": null,
    "tags": "focus,deep-work,pomodoro",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "hydrate-upon-waking",
    "name": "Hydrate Upon Waking",
    "domain": "nutrition",
    "category": "hydration",
    "summary": "Replenishes fluids after sleep; boosts alertness.",
    "goal_type": "bool",
    "default_target": null,
    "min_viable": "Drink a half cup of water.",
    "time_windows": [{ "start": "06:00", "end": "09:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Keep a glass by the bed.",
    "equipment": "",
    "contraindications": "",
    "difficulty": "easy",
    "estimated_minutes": 1,
    "coach_copy": null,
    "tags": "hydration,morning,energy",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "fruit-with-lunch",
    "name": "Add Fruit to Lunch",
    "domain": "nutrition",
    "category": "veggies-fruits",
    "summary": "Adds fiber and micronutrients to mid-day meal.",
    "goal_type": "bool",
    "default_target": null,
    "min_viable": "Pack one apple or orange.",
    "time_windows": [{ "start": "11:00", "end": "14:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Add to lunchbox packing.",
    "equipment": "",
    "contraindications": "",
    "difficulty": "easy",
    "estimated_minutes": 1,
    "coach_copy": null,
    "tags": "fruit,lunch,fiber",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "greek-yogurt-snack",
    "name": "Greek Yogurt Snack",
    "domain": "nutrition",
    "category": "protein",
    "summary": "Convenient protein to curb afternoon cravings.",
    "goal_type": "bool",
    "default_target": null,
    "min_viable": "Keep one single-serve yogurt on hand.",
    "time_windows": [{ "start": "14:00", "end": "17:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Pair with berries or nuts.",
    "equipment": "",
    "contraindications": "Consider dairy intolerance.",
    "difficulty": "easy",
    "estimated_minutes": 2,
    "coach_copy": null,
    "tags": "snack,protein,cravings",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "strength-2xwk",
    "name": "Strength Train 2×/Week",
    "domain": "exercise",
    "category": "strength",
    "summary": "Maintains muscle and bone density.",
    "goal_type": "count",
    "default_target": 2.0,
    "min_viable": "Do one set of a compound move.",
    "time_windows": [{ "start": "07:00", "end": "20:00" }],
    "suggested_rules": [{ "type": "weekly", "params": {"days_per_week":2} }],
    "cues_and_stacking": "Calendar Mon/Thu.",
    "equipment": "dumbbells or bodyweight",
    "contraindications": "",
    "difficulty": "medium",
    "estimated_minutes": 30,
    "coach_copy": null,
    "tags": "strength,training,muscle",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "micro-cleanup-5",
    "name": "Micro Cleanup (5 min)",
    "domain": "recovery",
    "category": "environment",
    "summary": "Fast reset to reduce clutter buildup.",
    "goal_type": "duration",
    "default_target": 5.0,
    "min_viable": "Clear one surface.",
    "time_windows": [{ "start": "19:00", "end": "21:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "After dinner dishes.",
    "equipment": "",
    "contraindications": "",
    "difficulty": "easy",
    "estimated_minutes": 5,
    "coach_copy": null,
    "tags": "cleanup,environment,stress",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "nature-time-15",
    "name": "Time in Nature (15 min)",
    "domain": "recovery",
    "category": "outdoors",
    "summary": "Improves mood and attention restoration.",
    "goal_type": "duration",
    "default_target": 15.0,
    "min_viable": "Sit outside for 3 minutes.",
    "time_windows": [{ "start": "12:00", "end": "18:00" }],
    "suggested_rules": [{ "type": "weekly", "params": {"days_per_week":3} }],
    "cues_and_stacking": "Walk a green route.",
    "equipment": "",
    "contraindications": "",
    "difficulty": "easy",
    "estimated_minutes": 15,
    "coach_copy": null,
    "tags": "nature,green,attention",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "social-checkin",
    "name": "Daily Social Check-In",
    "domain": "recovery",
    "category": "social",
    "summary": "Nurture relationships for wellbeing.",
    "goal_type": "bool",
    "default_target": null,
    "min_viable": "Send a quick message to one person.",
    "time_windows": [{ "start": "12:00", "end": "21:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Right after lunch break.",
    "equipment": "phone",
    "contraindications": "",
    "difficulty": "easy",
    "estimated_minutes": 2,
    "coach_copy": null,
    "tags": "social,connection,relationships",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "alcohol-free-days-2wk",
    "name": "Two Alcohol-Free Days per Week",
    "domain": "recovery",
    "category": "alcohol",
    "summary": "Supports recovery and sleep quality.",
    "goal_type": "count",
    "default_target": 2.0,
    "min_viable": "Plan one alcohol-free day this week.",
    "time_windows": [{ "start": "00:00", "end": "23:59" }],
    "suggested_rules": [{ "type": "weekly", "params": {"days_per_week":2} }],
    "cues_and_stacking": "Choose weekdays to start.",
    "equipment": "",
    "contraindications": "",
    "difficulty": "medium",
    "estimated_minutes": 0,
    "coach_copy": null,
    "tags": "alcohol,recovery,sleep",
    "sources": "Perplexity deep research"
  }
  ]'::jsonb;
BEGIN
  PERFORM public.rpc_upsert_habit_templates(v_payload);
END;
$$;