DO $$
DECLARE
  v_payload jsonb := '[
  {
    "slug": "whole-fruit-dessert",
    "name": "Have Whole Fruit for Dessert",
    "domain": "nutrition",
    "category": "sugar-reduction",
    "summary": "Swap sweets for fruit to cut added sugar while keeping satisfaction.",
    "goal_type": "bool",
    "default_target": null,
    "min_viable": "Choose fruit once after dinner.",
    "time_windows": [{ "start": "18:00", "end": "22:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Put fruit bowl on the counter.",
    "equipment": "",
    "contraindications": "",
    "difficulty": "easy",
    "estimated_minutes": 2,
    "coach_copy": null,
    "tags": "dessert,fruit,sugar-reduction",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "water-before-meals-8oz",
    "name": "Drink 8 oz Water Before Meals",
    "domain": "nutrition",
    "category": "hydration",
    "summary": "Pre-meal hydration can aid appetite regulation and digestion.",
    "goal_type": "count",
    "default_target": 1.0,
    "min_viable": "Take 4 sips before one meal.",
    "time_windows": [{ "start": "11:00", "end": "20:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Keep a glass by your plate.",
    "equipment": "glass",
    "contraindications": "Adjust for fluid-restricted conditions.",
    "difficulty": "easy",
    "estimated_minutes": 1,
    "coach_copy": null,
    "tags": "water,hydration,meals",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "veggie-prep-10",
    "name": "Veggie Prep (10 min)",
    "domain": "nutrition",
    "category": "prep",
    "summary": "Prepping veggies increases likelihood of eating them.",
    "goal_type": "duration",
    "default_target": 10.0,
    "min_viable": "Wash and cut one vegetable.",
    "time_windows": [{ "start": "16:00", "end": "19:00" }],
    "suggested_rules": [{ "type": "weekly", "params": {"days_per_week":3} }],
    "cues_and_stacking": "Do right after groceries.",
    "equipment": "knife,containers",
    "contraindications": "",
    "difficulty": "easy",
    "estimated_minutes": 10,
    "coach_copy": null,
    "tags": "prep,vegetables,planning",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "pack-healthy-snack",
    "name": "Pack a Healthy Snack",
    "domain": "nutrition",
    "category": "snacks",
    "summary": "Having a ready option reduces impulse junk choices.",
    "goal_type": "bool",
    "default_target": null,
    "min_viable": "Pack one piece of fruit or nuts.",
    "time_windows": [{ "start": "07:00", "end": "10:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Add to morning out-the-door routine.",
    "equipment": "bag/container",
    "contraindications": "",
    "difficulty": "easy",
    "estimated_minutes": 2,
    "coach_copy": null,
    "tags": "snack,planning,nutrition",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "soup-or-salad-first",
    "name": "Soup or Salad First",
    "domain": "nutrition",
    "category": "portion",
    "summary": "Starting with low-calorie-dense foods can improve fullness.",
    "goal_type": "bool",
    "default_target": null,
    "min_viable": "Begin one meal with a simple salad.",
    "time_windows": [{ "start": "11:00", "end": "20:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Prep salad greens on Sundays.",
    "equipment": "",
    "contraindications": "",
    "difficulty": "easy",
    "estimated_minutes": 5,
    "coach_copy": null,
    "tags": "portion,appetite,vegetables",
    "sources": "Perplexity deep research"
  },

  {
    "slug": "farmer-carry-2",
    "name": "Farmer Carry (2 min total)",
    "domain": "exercise",
    "category": "strength",
    "summary": "Builds grip and trunk stability using simple carries.",
    "goal_type": "duration",
    "default_target": 2.0,
    "min_viable": "Carry weights for 30 seconds.",
    "time_windows": [{ "start": "08:00", "end": "18:00" }],
    "suggested_rules": [{ "type": "weekly", "params": {"days_per_week":3} }],
    "cues_and_stacking": "Do after a strength set.",
    "equipment": "dumbbells/kettlebells",
    "contraindications": "Modify for back or grip pain.",
    "difficulty": "medium",
    "estimated_minutes": 2,
    "coach_copy": null,
    "tags": "carry,grip,core,strength",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "sit-stand-8",
    "name": "Sit-to-Stand (8 reps)",
    "domain": "exercise",
    "category": "daily-activity",
    "summary": "Simple lower-body strength and mobility without equipment.",
    "goal_type": "count",
    "default_target": 8.0,
    "min_viable": "Do 3 reps from a chair.",
    "time_windows": [{ "start": "09:00", "end": "19:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Do at each coffee break.",
    "equipment": "chair",
    "contraindications": "Use higher chair if knee pain.",
    "difficulty": "easy",
    "estimated_minutes": 2,
    "coach_copy": null,
    "tags": "legs,functional,strength",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "ankle-circles-60s",
    "name": "Ankle Circles (60s)",
    "domain": "exercise",
    "category": "mobility",
    "summary": "Improves ankle mobility and circulation, helpful for runners and desk work.",
    "goal_type": "duration",
    "default_target": 1.0,
    "min_viable": "Do 20 seconds per side.",
    "time_windows": [{ "start": "10:00", "end": "18:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "During meetings or while seated.",
    "equipment": "",
    "contraindications": "Avoid sharp pain.",
    "difficulty": "easy",
    "estimated_minutes": 1,
    "coach_copy": null,
    "tags": "ankle,mobility,desk",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "clamshells-20",
    "name": "Clamshells (20 reps)",
    "domain": "exercise",
    "category": "strength",
    "summary": "Targets glute medius for hip/knee stability.",
    "goal_type": "count",
    "default_target": 20.0,
    "min_viable": "Do 8 controlled reps per side.",
    "time_windows": [{ "start": "17:00", "end": "21:00" }],
    "suggested_rules": [{ "type": "weekly", "params": {"days_per_week":3} }],
    "cues_and_stacking": "Add to mobility flow before bed.",
    "equipment": "miniband (optional)",
    "contraindications": "Stop with hip pain.",
    "difficulty": "easy",
    "estimated_minutes": 4,
    "coach_copy": null,
    "tags": "glutes,hips,strength",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "band-face-pulls-20",
    "name": "Band Face Pulls (20 reps)",
    "domain": "exercise",
    "category": "strength",
    "summary": "Strengthens rear delts and upper back to counter desk posture.",
    "goal_type": "count",
    "default_target": 20.0,
    "min_viable": "Do 8 reps with a light band.",
    "time_windows": [{ "start": "08:00", "end": "18:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Keep band visible at desk.",
    "equipment": "resistance band",
    "contraindications": "Modify for shoulder pain.",
    "difficulty": "easy",
    "estimated_minutes": 3,
    "coach_copy": null,
    "tags": "upper-back,posture,shoulders",
    "sources": "Perplexity deep research"
  }
  ]'::jsonb;
BEGIN
  PERFORM public.rpc_upsert_habit_templates(v_payload);
END;
$$;