-- Batch 15: Add 10 new habit templates (3N/3E/4R)
-- Expected totals after: Total 153, Nutrition 51, Exercise 51, Recovery 51

DO $$
DECLARE
  v_payload jsonb := $json$
[
  {
    "slug": "chia-seeds-1tbsp",
    "name": "Add 1 Tbsp Chia Seeds",
    "domain": "nutrition",
    "category": "healthy-fats",
    "summary": "Adds fiber and omega-3 ALA for heart and gut health.",
    "goal_type": "count",
    "default_target": 1.0,
    "min_viable": "Sprinkle 1 teaspoon on yogurt or oats.",
    "time_windows": [{ "start": "07:00", "end": "12:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Keep a jar with breakfast items.",
    "equipment": "",
    "contraindications": "Increase gradually; consider GI sensitivity.",
    "difficulty": "easy",
    "estimated_minutes": 1,
    "coach_copy": null,
    "tags": "chia,fiber,omega-3,healthy-fats",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "citrus-fruit-1",
    "name": "Eat 1 Citrus Fruit/Serving",
    "domain": "nutrition",
    "category": "veggies-fruits",
    "summary": "Vitamin C and polyphenols to support immune and vascular health.",
    "goal_type": "count",
    "default_target": 1.0,
    "min_viable": "Add a few orange slices.",
    "time_windows": [{ "start": "10:00", "end": "20:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Pack an orange with lunch.",
    "equipment": "",
    "contraindications": "Caution with reflux; rinse mouth after acidic foods.",
    "difficulty": "easy",
    "estimated_minutes": 2,
    "coach_copy": null,
    "tags": "citrus,vitamin-c,fruit,polyphenols",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "herbs-spices-1tsp",
    "name": "Add Herbs/Spices (1 tsp)",
    "domain": "nutrition",
    "category": "antioxidants",
    "summary": "Boosts flavor and antioxidants (e.g., turmeric, ginger, cinnamon, oregano).",
    "goal_type": "count",
    "default_target": 1.0,
    "min_viable": "A pinch on one meal.",
    "time_windows": [{ "start": "11:00", "end": "20:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Keep spice blends visible on counter.",
    "equipment": "",
    "contraindications": "Check interactions (e.g., cinnamon with certain meds).",
    "difficulty": "easy",
    "estimated_minutes": 1,
    "coach_copy": null,
    "tags": "spices,herbs,antioxidants,flavor",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "chin-tucks-10",
    "name": "Chin Tucks (10 reps)",
    "domain": "exercise",
    "category": "mobility",
    "summary": "Strengthens deep neck flexors and counters forward-head posture.",
    "goal_type": "count",
    "default_target": 10.0,
    "min_viable": "Do 3 gentle reps.",
    "time_windows": [{ "start": "10:00", "end": "18:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Add to every posture break.",
    "equipment": "",
    "contraindications": "Stop with dizziness or pain.",
    "difficulty": "easy",
    "estimated_minutes": 2,
    "coach_copy": null,
    "tags": "neck,posture,chin-tuck,mobility",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "hip-hinge-drill-10",
    "name": "Hip-Hinge Drill (10 reps)",
    "domain": "exercise",
    "category": "mobility",
    "summary": "Grooves the hinge pattern to protect the low back and load hips.",
    "goal_type": "count",
    "default_target": 10.0,
    "min_viable": "Do 4 reps with a broomstick along spine.",
    "time_windows": [{ "start": "09:00", "end": "18:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Before lifts or during desk breaks.",
    "equipment": "broomstick (optional)",
    "contraindications": "Limit range if back pain.",
    "difficulty": "easy",
    "estimated_minutes": 3,
    "coach_copy": null,
    "tags": "hinge,hips,back,mobility,skill",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "bear-crawl-30s",
    "name": "Bear Crawl (30s)",
    "domain": "exercise",
    "category": "core",
    "summary": "Core and shoulder stability with a short crawling pattern.",
    "goal_type": "duration",
    "default_target": 0.5,
    "min_viable": "10 seconds in place.",
    "time_windows": [{ "start": "07:00", "end": "18:00" }],
    "suggested_rules": [{ "type": "weekly", "params": {"days_per_week":3} }],
    "cues_and_stacking": "Add between strength sets.",
    "equipment": "",
    "contraindications": "Modify for wrist/shoulder issues; keep spine neutral.",
    "difficulty": "medium",
    "estimated_minutes": 1,
    "coach_copy": null,
    "tags": "core,crawl,stability,shoulders",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "herbal-tea-evening",
    "name": "Evening Herbal Tea",
    "domain": "recovery",
    "category": "wind-down",
    "summary": "Non-caffeinated tea ritual to cue relaxation before bed.",
    "goal_type": "bool",
    "default_target": null,
    "min_viable": "Sip a few warm mouthfuls.",
    "time_windows": [{ "start": "19:00", "end": "22:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Pair with digital sunset.",
    "equipment": "kettle/mug",
    "contraindications": "Check herb interactions; avoid late fluids if nocturia.",
    "difficulty": "easy",
    "estimated_minutes": 5,
    "coach_copy": null,
    "tags": "tea,wind-down,sleep,ritual",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "nap-15",
    "name": "Power Nap (15 min)",
    "domain": "recovery",
    "category": "restoration",
    "summary": "Short daytime nap to boost alertness and mood.",
    "goal_type": "duration",
    "default_target": 15.0,
    "min_viable": "Close eyes for 5 minutes.",
    "time_windows": [{ "start": "12:30", "end": "15:30" }],
    "suggested_rules": [{ "type": "weekly", "params": {"days_per_week":3} }],
    "cues_and_stacking": "Set a 20-minute timer (includes wind-down).",
    "equipment": "",
    "contraindications": "Avoid late naps if insomnia; adapt for shift work.",
    "difficulty": "easy",
    "estimated_minutes": 15,
    "coach_copy": null,
    "tags": "nap,alertness,recovery",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "sunset-outside-5",
    "name": "Catch the Sunset (5 min)",
    "domain": "recovery",
    "category": "circadian",
    "summary": "Evening outdoor light cue helps anchor circadian rhythm.",
    "goal_type": "duration",
    "default_target": 5.0,
    "min_viable": "Step outside for 2 minutes.",
    "time_windows": [{ "start": "17:30", "end": "21:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Take a post-dinner lap outside.",
    "equipment": "",
    "contraindications": "Weather/safety considerations.",
    "difficulty": "easy",
    "estimated_minutes": 5,
    "coach_copy": null,
    "tags": "sunset,light,circadian,sleep",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "nasal-breathing-5",
    "name": "Nasal Breathing Practice (5 min)",
    "domain": "recovery",
    "category": "breathwork",
    "summary": "Nasal-only easy breathing to encourage diaphragmatic pattern and calm.",
    "goal_type": "duration",
    "default_target": 5.0,
    "min_viable": "Do 60 seconds nasal-only.",
    "time_windows": [{ "start": "12:00", "end": "20:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Practice during a walk or between tasks.",
    "equipment": "",
    "contraindications": "Skip if congested or uncomfortable.",
    "difficulty": "easy",
    "estimated_minutes": 5,
    "coach_copy": null,
    "tags": "breathing,nasal,calm,parasympathetic",
    "sources": "Perplexity deep research"
  }
]
$json$::jsonb;
BEGIN
  PERFORM public.rpc_upsert_habit_templates(v_payload);
END;
$$;