-- Batch 2: Import 10 more habit templates (nutrition, exercise focus)
DO $$
DECLARE
  v_payload jsonb := '[
  {
    "slug": "30g-fiber-daily",
    "name": "Hit ~30g Fiber Daily",
    "domain": "nutrition",
    "category": "fiber",
    "summary": "Supports gut health, satiety, and metabolic markers.",
    "goal_type": "count",
    "default_target": 30.0,
    "min_viable": "Add one high-fiber food to one meal.",
    "time_windows": [{ "start": "07:00", "end": "22:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Add chia seeds, beans, or veggies to meals.",
    "equipment": "",
    "contraindications": "Increase gradually to avoid GI discomfort.",
    "difficulty": "medium",
    "estimated_minutes": 5,
    "coach_copy": null,
    "tags": "fiber,gut,fullness,metabolic",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "leafy-greens-x2",
    "name": "Eat 2 Servings of Leafy Greens",
    "domain": "nutrition",
    "category": "veggies",
    "summary": "Micronutrients and nitrates for heart health.",
    "goal_type": "count",
    "default_target": 2.0,
    "min_viable": "Add a side salad to one meal.",
    "time_windows": [{ "start": "07:00", "end": "22:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Keep pre-washed greens in the fridge.",
    "equipment": "",
    "contraindications": "",
    "difficulty": "easy",
    "estimated_minutes": 5,
    "coach_copy": null,
    "tags": "greens,vegetables,heart,vitamins",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "swap-soda-for-water",
    "name": "Swap Sugary Drink for Water",
    "domain": "nutrition",
    "category": "hydration",
    "summary": "Reduces sugar intake and stabilizes energy.",
    "goal_type": "bool",
    "default_target": null,
    "min_viable": "Replace one soda/juice today with water.",
    "time_windows": [{ "start": "10:00", "end": "20:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Carry flavored seltzer as a backup.",
    "equipment": "",
    "contraindications": "",
    "difficulty": "easy",
    "estimated_minutes": 0,
    "coach_copy": null,
    "tags": "sugar,hydration,energy",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "protein-25g-meal",
    "name": "Include ~25g Protein per Meal",
    "domain": "nutrition",
    "category": "protein",
    "summary": "Improves satiety and muscle recovery.",
    "goal_type": "count",
    "default_target": 25.0,
    "min_viable": "Add eggs, yogurt, or beans to one meal.",
    "time_windows": [{ "start": "06:00", "end": "22:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Prep protein ahead on Sundays.",
    "equipment": "",
    "contraindications": "",
    "difficulty": "easy",
    "estimated_minutes": 10,
    "coach_copy": null,
    "tags": "protein,satiety,muscle",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "mindful-eating-5",
    "name": "Practice Mindful Eating (5 min)",
    "domain": "nutrition",
    "category": "mindful-eating",
    "summary": "Enhances hunger/fullness awareness and portion control.",
    "goal_type": "duration",
    "default_target": 5.0,
    "min_viable": "Take 3 slow breaths before eating.",
    "time_windows": [{ "start": "07:00", "end": "22:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Put phone away during meals.",
    "equipment": "",
    "contraindications": "",
    "difficulty": "easy",
    "estimated_minutes": 5,
    "coach_copy": null,
    "tags": "mindful,portion,awareness",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "zone2-cardio-20",
    "name": "Do 20 Minutes of Zone 2 Cardio",
    "domain": "exercise",
    "category": "cardio",
    "summary": "Builds aerobic base and mitochondrial health.",
    "goal_type": "duration",
    "default_target": 20.0,
    "min_viable": "Take a brisk 5-minute walk.",
    "time_windows": [{ "start": "06:00", "end": "20:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Use stairs; park farther away.",
    "equipment": "shoes",
    "contraindications": "Consult doctor if heart/respiratory issues.",
    "difficulty": "easy",
    "estimated_minutes": 20,
    "coach_copy": null,
    "tags": "zone2,cardio,aerobic",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "mobility-10",
    "name": "Mobility Work (10 min)",
    "domain": "exercise",
    "category": "mobility",
    "summary": "Improves range of motion and reduces stiffness.",
    "goal_type": "duration",
    "default_target": 10.0,
    "min_viable": "Do one mobility drill for 2 minutes.",
    "time_windows": [{ "start": "06:00", "end": "22:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Before/after workouts; during TV.",
    "equipment": "mat",
    "contraindications": "",
    "difficulty": "easy",
    "estimated_minutes": 10,
    "coach_copy": null,
    "tags": "mobility,flexibility,stretch",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "squats-3-sets",
    "name": "3 Sets of Bodyweight Squats",
    "domain": "exercise",
    "category": "strength",
    "summary": "Lower-body strength and joint health.",
    "goal_type": "count",
    "default_target": 3.0,
    "min_viable": "Do 5 squats right now.",
    "time_windows": [{ "start": "06:00", "end": "22:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "After brushing teeth; pre-shower.",
    "equipment": "",
    "contraindications": "Modify if knee pain.",
    "difficulty": "easy",
    "estimated_minutes": 6,
    "coach_copy": null,
    "tags": "squats,strength,legs",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "posture-breaks-hourly",
    "name": "Take Posture Breaks Hourly",
    "domain": "exercise",
    "category": "posture",
    "summary": "Reduces stiffness; supports back/neck health.",
    "goal_type": "bool",
    "default_target": null,
    "min_viable": "Stand and stretch for 30 seconds once.",
    "time_windows": [{ "start": "09:00", "end": "18:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Use timer or watch reminder.",
    "equipment": "",
    "contraindications": "",
    "difficulty": "easy",
    "estimated_minutes": 2,
    "coach_copy": null,
    "tags": "posture,desk,breaks",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "plank-60s",
    "name": "Plank for 60 Seconds",
    "domain": "exercise",
    "category": "core",
    "summary": "Builds trunk stability and posture.",
    "goal_type": "duration",
    "default_target": 60.0,
    "min_viable": "Hold a 15-second plank.",
    "time_windows": [{ "start": "06:00", "end": "22:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "After coffee or before shower.",
    "equipment": "mat",
    "contraindications": "Modify for back pain.",
    "difficulty": "medium",
    "estimated_minutes": 2,
    "coach_copy": null,
    "tags": "plank,core,stability",
    "sources": "Perplexity deep research"
  }
  ]'::jsonb;
BEGIN
  PERFORM public.rpc_upsert_habit_templates(v_payload);
END;
$$;