DO $$
DECLARE
  v_payload jsonb := '[
  {
    "slug": "cruciferous-cup-1",
    "name": "Eat 1 Cup of Cruciferous Veg",
    "domain": "nutrition",
    "category": "veggies-fruits",
    "summary": "Add broccoli, cauliflower, kale, or cabbage for fiber and phytonutrients.",
    "goal_type": "count",
    "default_target": 1.0,
    "min_viable": "Add 1/2 cup to one meal.",
    "time_windows": [{ "start": "11:00", "end": "20:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Toss into stir-fry or salad.",
    "equipment": "",
    "contraindications": "Adjust for GI sensitivity.",
    "difficulty": "easy",
    "estimated_minutes": 4,
    "coach_copy": null,
    "tags": "cruciferous,broccoli,cauliflower,vegetables",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "savory-breakfast-swap",
    "name": "Savory Breakfast Swap",
    "domain": "nutrition",
    "category": "sugar-reduction",
    "summary": "Choose a savory/protein-first breakfast to reduce morning glucose spikes.",
    "goal_type": "bool",
    "default_target": null,
    "min_viable": "Swap sweet cereal for eggs or yogurt once.",
    "time_windows": [{ "start": "06:00", "end": "10:30" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Prep hard-boiled eggs ahead.",
    "equipment": "",
    "contraindications": "Adjust for dietary restrictions.",
    "difficulty": "easy",
    "estimated_minutes": 5,
    "coach_copy": null,
    "tags": "breakfast,protein,satiety,sugar",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "water-2l-day",
    "name": "Reach 2 Liters of Water Today",
    "domain": "nutrition",
    "category": "hydration",
    "summary": "Supports hydration and energy; adjust by climate/activity and clinician advice.",
    "goal_type": "count",
    "default_target": 2.0,
    "min_viable": "Finish one 16 oz (500 mL) bottle.",
    "time_windows": [{ "start": "07:00", "end": "21:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Keep a filled bottle at desk.",
    "equipment": "water bottle",
    "contraindications": "Adjust for fluid-restricted conditions.",
    "difficulty": "easy",
    "estimated_minutes": 2,
    "coach_copy": null,
    "tags": "hydration,water,energy",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "protein-snack-15g",
    "name": "Afternoon Protein Snack (15 g)",
    "domain": "nutrition",
    "category": "protein",
    "summary": "Protein between meals can curb cravings and support lean mass.",
    "goal_type": "count",
    "default_target": 15.0,
    "min_viable": "Hit at least 10 g once.",
    "time_windows": [{ "start": "14:00", "end": "17:30" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Pack Greek yogurt or a small shake.",
    "equipment": "",
    "contraindications": "Adjust for kidney disease per clinician.",
    "difficulty": "easy",
    "estimated_minutes": 3,
    "coach_copy": null,
    "tags": "protein,snack,satiety",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "vinegar-with-meal-1tbsp",
    "name": "Vinegar with Meal (1 tbsp)",
    "domain": "nutrition",
    "category": "sugar-reduction",
    "summary": "1 tbsp vinegar with a meal may blunt postprandial glucose; use food-safe vinegar.",
    "goal_type": "count",
    "default_target": 1.0,
    "min_viable": "Use 1 tsp if sensitive.",
    "time_windows": [{ "start": "11:00", "end": "20:30" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Make a quick vinaigrette.",
    "equipment": "",
    "contraindications": "Avoid if esophagitis/ulcer; dilute to protect teeth.",
    "difficulty": "easy",
    "estimated_minutes": 1,
    "coach_copy": null,
    "tags": "vinegar,glucose,meal",
    "sources": "Perplexity deep research"
  },

  {
    "slug": "air-squats-20",
    "name": "Air Squats (20 reps)",
    "domain": "exercise",
    "category": "strength",
    "summary": "Quick lower-body strength builder requiring no equipment.",
    "goal_type": "count",
    "default_target": 20.0,
    "min_viable": "Do 8 controlled reps.",
    "time_windows": [{ "start": "09:00", "end": "19:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Do during a mid-day break.",
    "equipment": "",
    "contraindications": "Modify depth for knee pain.",
    "difficulty": "easy",
    "estimated_minutes": 3,
    "coach_copy": null,
    "tags": "legs,strength,functional",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "reverse-lunges-16",
    "name": "Reverse Lunges (8/side)",
    "domain": "exercise",
    "category": "strength",
    "summary": "Single-leg strength to improve balance and hip/knee control.",
    "goal_type": "count",
    "default_target": 16.0,
    "min_viable": "Do 6 total holding support.",
    "time_windows": [{ "start": "08:00", "end": "20:00" }],
    "suggested_rules": [{ "type": "weekly", "params": {"days_per_week":3} }],
    "cues_and_stacking": "Add after squats or a walk.",
    "equipment": "",
    "contraindications": "Modify for knee pain or balance limits.",
    "difficulty": "medium",
    "estimated_minutes": 4,
    "coach_copy": null,
    "tags": "lunges,legs,balance,strength",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "hollow-hold-30s",
    "name": "Hollow Hold (30s)",
    "domain": "exercise",
    "category": "core",
    "summary": "Core isometric for trunk stability; scale by tucking knees.",
    "goal_type": "duration",
    "default_target": 0.5,
    "min_viable": "Hold 10 seconds tucked.",
    "time_windows": [{ "start": "08:00", "end": "20:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Pair with plank routine.",
    "equipment": "mat",
    "contraindications": "Modify for neck/low-back discomfort.",
    "difficulty": "medium",
    "estimated_minutes": 1,
    "coach_copy": null,
    "tags": "core,isometric,stability",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "thoracic-rotation-2",
    "name": "Thoracic Rotation (2 min)",
    "domain": "exercise",
    "category": "mobility",
    "summary": "Opens mid-back; helpful for desk posture and overhead mobility.",
    "goal_type": "duration",
    "default_target": 2.0,
    "min_viable": "Do 60 seconds of open-book turns.",
    "time_windows": [{ "start": "10:00", "end": "18:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Do during posture breaks.",
    "equipment": "",
    "contraindications": "Avoid painful end ranges.",
    "difficulty": "easy",
    "estimated_minutes": 2,
    "coach_copy": null,
    "tags": "thoracic,spine,mobility,desk",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "wrist-mobility-2",
    "name": "Wrist Mobility (2 min)",
    "domain": "exercise",
    "category": "mobility",
    "summary": "Gentle flexion/extension/circles to reduce desk/typing stiffness.",
    "goal_type": "duration",
    "default_target": 2.0,
    "min_viable": "Do 60 seconds of circles.",
    "time_windows": [{ "start": "09:00", "end": "17:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Add to 20-20-20 eye breaks.",
    "equipment": "",
    "contraindications": "Skip if acute wrist injury.",
    "difficulty": "easy",
    "estimated_minutes": 2,
    "coach_copy": null,
    "tags": "wrist,mobility,desk",
    "sources": "Perplexity deep research"
  }
  ]'::jsonb;
BEGIN
  PERFORM public.rpc_upsert_habit_templates(v_payload);
END;
$$;