DO $$
DECLARE
  v_payload jsonb := '[
  {
    "slug": "quarter-plate-protein",
    "name": "Quarter Plate Protein",
    "domain": "nutrition",
    "category": "portion",
    "summary": "Anchor meals with ~25% quality protein to improve satiety and recovery.",
    "goal_type": "bool",
    "default_target": null,
    "min_viable": "Add one palm-sized protein at one meal.",
    "time_windows": [{ "start": "11:00", "end": "20:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Plan protein first when building the plate.",
    "equipment": "",
    "contraindications": "Adjust for dietary preferences or restrictions.",
    "difficulty": "easy",
    "estimated_minutes": 3,
    "coach_copy": null,
    "tags": "protein,portion,satiety",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "veg-at-dinner",
    "name": "Add Vegetables at Dinner",
    "domain": "nutrition",
    "category": "veggies-fruits",
    "summary": "Boosts fiber, micronutrients, and fullness at the evening meal.",
    "goal_type": "bool",
    "default_target": null,
    "min_viable": "Add one fist of any vegetable.",
    "time_windows": [{ "start": "17:00", "end": "21:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Steam frozen veggies while cooking main dish.",
    "equipment": "",
    "contraindications": "",
    "difficulty": "easy",
    "estimated_minutes": 5,
    "coach_copy": null,
    "tags": "vegetables,fiber,dinner",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "bird-dog-20",
    "name": "Bird-Dog (10/side)",
    "domain": "exercise",
    "category": "core",
    "summary": "Builds spinal stability and improves coordination.",
    "goal_type": "count",
    "default_target": 20.0,
    "min_viable": "Do 6 reps total with control.",
    "time_windows": [{ "start": "07:00", "end": "20:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Add to morning warm-up.",
    "equipment": "mat",
    "contraindications": "Modify range for low-back pain.",
    "difficulty": "easy",
    "estimated_minutes": 4,
    "coach_copy": null,
    "tags": "core,stability,balance",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "side-plank-30s",
    "name": "Side Plank (30s/side)",
    "domain": "exercise",
    "category": "core",
    "summary": "Targets lateral core for posture and back health.",
    "goal_type": "duration",
    "default_target": 1.0,
    "min_viable": "Hold 10s/side with knees bent.",
    "time_windows": [{ "start": "08:00", "end": "20:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Do before or after main workout.",
    "equipment": "mat",
    "contraindications": "Modify for shoulder discomfort.",
    "difficulty": "medium",
    "estimated_minutes": 1,
    "coach_copy": null,
    "tags": "core,side-plank,posture",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "wall-angels-10",
    "name": "Wall Angels (10 reps)",
    "domain": "exercise",
    "category": "mobility",
    "summary": "Opens chest and improves thoracic/shoulder mobility.",
    "goal_type": "count",
    "default_target": 10.0,
    "min_viable": "Do 4 controlled reps.",
    "time_windows": [{ "start": "09:00", "end": "18:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Insert during mid-day posture break.",
    "equipment": "",
    "contraindications": "Reduce range if painful.",
    "difficulty": "easy",
    "estimated_minutes": 3,
    "coach_copy": null,
    "tags": "mobility,posture,shoulders",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "doorway-pec-stretch-2",
    "name": "Doorway Pec Stretch (2 min)",
    "domain": "exercise",
    "category": "mobility",
    "summary": "Counters rounded shoulders from desk work.",
    "goal_type": "duration",
    "default_target": 2.0,
    "min_viable": "Hold 30 seconds gently.",
    "time_windows": [{ "start": "10:00", "end": "18:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Do at each bathroom break.",
    "equipment": "",
    "contraindications": "Avoid sharp shoulder pain.",
    "difficulty": "easy",
    "estimated_minutes": 2,
    "coach_copy": null,
    "tags": "mobility,pecs,posture",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "paper-reading-10",
    "name": "Read Paper Book (10 min)",
    "domain": "recovery",
    "category": "wind-down",
    "summary": "Low-stimulation activity that eases transition to sleep.",
    "goal_type": "duration",
    "default_target": 10.0,
    "min_viable": "Read one page on paper.",
    "time_windows": [{ "start": "20:00", "end": "23:30" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Pair with digital sunset.",
    "equipment": "paper book",
    "contraindications": "",
    "difficulty": "easy",
    "estimated_minutes": 10,
    "coach_copy": null,
    "tags": "reading,wind-down,sleep",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "eye-breaks-20-20-20",
    "name": "Eye Breaks (20-20-20)",
    "domain": "recovery",
    "category": "screen-hygiene",
    "summary": "Reduces eye strain: every 20 minutes, look 20 feet away for 20 seconds.",
    "goal_type": "count",
    "default_target": 3.0,
    "min_viable": "Do one 20-second break this afternoon.",
    "time_windows": [{ "start": "09:00", "end": "17:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Use a timer or app reminder.",
    "equipment": "",
    "contraindications": "",
    "difficulty": "easy",
    "estimated_minutes": 2,
    "coach_copy": null,
    "tags": "eyes,screen,breaks",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "earlier-dinner-2h",
    "name": "Finish Dinner ≥2h Before Bed",
    "domain": "recovery",
    "category": "sleep-hygiene",
    "summary": "Earlier meals can improve sleep latency and quality.",
    "goal_type": "bool",
    "default_target": null,
    "min_viable": "Aim for ≥1 hour buffer tonight.",
    "time_windows": [{ "start": "17:00", "end": "21:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Set a kitchen-close alarm.",
    "equipment": "",
    "contraindications": "Adjust for shift work or glucose needs.",
    "difficulty": "medium",
    "estimated_minutes": 0,
    "coach_copy": null,
    "tags": "sleep,digestion,meal-timing",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "neck-stretch-3",
    "name": "Neck Stretch (3 min)",
    "domain": "recovery",
    "category": "mobility",
    "summary": "Eases tension from desk posture and screen use.",
    "goal_type": "duration",
    "default_target": 3.0,
    "min_viable": "Do 60 seconds of gentle neck mobility.",
    "time_windows": [{ "start": "14:00", "end": "20:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Add to afternoon reset.",
    "equipment": "",
    "contraindications": "Avoid end-range if painful or dizzy.",
    "difficulty": "easy",
    "estimated_minutes": 3,
    "coach_copy": null,
    "tags": "neck,stretch,posture",
    "sources": "Perplexity deep research"
  }
  ]'::jsonb;
BEGIN
  PERFORM public.rpc_upsert_habit_templates(v_payload);
END;
$$;