DO $$
DECLARE
  v_payload jsonb := '[
  {
    "slug": "side-salad-lunch",
    "name": "Side Salad at Lunch",
    "domain": "nutrition",
    "category": "veggies-fruits",
    "summary": "Adds fiber and micronutrients with minimal prep.",
    "goal_type": "bool",
    "default_target": null,
    "min_viable": "Add a handful of greens.",
    "time_windows": [{ "start": "11:00", "end": "14:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Assemble while heating main dish.",
    "equipment": "",
    "contraindications": "",
    "difficulty": "easy",
    "estimated_minutes": 3,
    "coach_copy": null,
    "tags": "salad,lunch,vegetables,fiber",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "rainbow-veg-3colors",
    "name": "3 Colors of Veg Today",
    "domain": "nutrition",
    "category": "veggies-fruits",
    "summary": "Color variety boosts phytonutrients and fiber.",
    "goal_type": "count",
    "default_target": 3.0,
    "min_viable": "Include two colors once.",
    "time_windows": [{ "start": "10:00", "end": "21:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Buy a pre-cut mix to simplify.",
    "equipment": "",
    "contraindications": "",
    "difficulty": "easy",
    "estimated_minutes": 5,
    "coach_copy": null,
    "tags": "vegetables,colors,phytonutrients",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "nuts-seeds-tbsp",
    "name": "Add 1 Tbsp Nuts/Seeds",
    "domain": "nutrition",
    "category": "healthy-fats",
    "summary": "Adds healthy fats and minerals; supports satiety.",
    "goal_type": "count",
    "default_target": 1.0,
    "min_viable": "Sprinkle a teaspoon on a meal.",
    "time_windows": [{ "start": "07:00", "end": "20:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Keep a jar on the counter.",
    "equipment": "",
    "contraindications": "Allergy caution.",
    "difficulty": "easy",
    "estimated_minutes": 1,
    "coach_copy": null,
    "tags": "nuts,seeds,healthy-fats,satiety",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "added-sugar-25g",
    "name": "Keep Added Sugar ≤25g",
    "domain": "nutrition",
    "category": "sugar-reduction",
    "summary": "Lower added sugar to support metabolic health.",
    "goal_type": "count",
    "default_target": 25.0,
    "min_viable": "Swap dessert for whole fruit once.",
    "time_windows": [{ "start": "07:00", "end": "22:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Check labels on snacks/drinks.",
    "equipment": "",
    "contraindications": "Adjust for athletic needs or medical guidance.",
    "difficulty": "medium",
    "estimated_minutes": 2,
    "coach_copy": null,
    "tags": "sugar,labels,metabolic-health",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "dead-hang-30s",
    "name": "Dead Hang (30s)",
    "domain": "exercise",
    "category": "strength",
    "summary": "Builds grip and decompresses shoulders/posture.",
    "goal_type": "duration",
    "default_target": 0.5,
    "min_viable": "Hang 10 seconds with support.",
    "time_windows": [{ "start": "08:00", "end": "18:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Do after a bathroom break.",
    "equipment": "pull-up bar",
    "contraindications": "Modify for shoulder pain or instability.",
    "difficulty": "medium",
    "estimated_minutes": 1,
    "coach_copy": null,
    "tags": "grip,shoulders,posture,strength",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "step-ups-20",
    "name": "20 Step-Ups",
    "domain": "exercise",
    "category": "strength",
    "summary": "Single-leg strength and balance with minimal gear.",
    "goal_type": "count",
    "default_target": 20.0,
    "min_viable": "Do 8 total on a low step.",
    "time_windows": [{ "start": "09:00", "end": "19:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "During TV ads or kettle boil.",
    "equipment": "sturdy step",
    "contraindications": "Modify for knee pain or poor balance.",
    "difficulty": "easy",
    "estimated_minutes": 4,
    "coach_copy": null,
    "tags": "legs,balance,strength",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "jump-rope-2",
    "name": "Jump Rope (2 min)",
    "domain": "exercise",
    "category": "cardio",
    "summary": "Quick cardio burst to elevate heart rate.",
    "goal_type": "duration",
    "default_target": 2.0,
    "min_viable": "Do 30 seconds of low-impact steps.",
    "time_windows": [{ "start": "07:00", "end": "18:00" }],
    "suggested_rules": [{ "type": "weekly", "params": {"days_per_week":3} }],
    "cues_and_stacking": "Before a shower or workout.",
    "equipment": "jump rope",
    "contraindications": "Avoid with acute joint pain; choose low-impact alternative.",
    "difficulty": "medium",
    "estimated_minutes": 2,
    "coach_copy": null,
    "tags": "cardio,vo2,energy",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "hip-flexor-stretch-2",
    "name": "Hip Flexor Stretch (2 min)",
    "domain": "exercise",
    "category": "mobility",
    "summary": "Counters sitting; eases anterior hip tightness.",
    "goal_type": "duration",
    "default_target": 2.0,
    "min_viable": "Hold 30 seconds gently per side.",
    "time_windows": [{ "start": "12:00", "end": "20:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "After long sitting blocks.",
    "equipment": "",
    "contraindications": "Avoid pain; reduce depth for knee sensitivity.",
    "difficulty": "easy",
    "estimated_minutes": 2,
    "coach_copy": null,
    "tags": "hips,stretch,mobility",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "legs-up-wall-5",
    "name": "Legs-Up-the-Wall (5 min)",
    "domain": "recovery",
    "category": "relaxation",
    "summary": "Gentle inversion to promote relaxation and reduce leg fatigue.",
    "goal_type": "duration",
    "default_target": 5.0,
    "min_viable": "Hold for 2 minutes.",
    "time_windows": [{ "start": "19:00", "end": "22:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Add to pre-bed wind-down.",
    "equipment": "wall/pillow",
    "contraindications": "Avoid if dizziness or elevated pressure concerns.",
    "difficulty": "easy",
    "estimated_minutes": 5,
    "coach_copy": null,
    "tags": "relaxation,recovery,inversion",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "body-scan-5",
    "name": "Body Scan (5 min)",
    "domain": "recovery",
    "category": "mindfulness",
    "summary": "Systematic attention to relax tension and improve awareness.",
    "goal_type": "duration",
    "default_target": 5.0,
    "min_viable": "Scan head/neck only for 60s.",
    "time_windows": [{ "start": "20:00", "end": "23:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Pair with bedtime routine.",
    "equipment": "",
    "contraindications": "",
    "difficulty": "easy",
    "estimated_minutes": 5,
    "coach_copy": null,
    "tags": "mindfulness,relaxation,stress",
    "sources": "Perplexity deep research"
  }
  ]'::jsonb;
BEGIN
  PERFORM public.rpc_upsert_habit_templates(v_payload);
END;
$$;