-- Batch 14: Add 10 new habit templates (4N/4E/2R)
-- Expected totals after: Total 143, Nutrition 48, Exercise 48, Recovery 47

DO $$
DECLARE
  v_payload jsonb := $json$
[
  /* -------------------- NUTRITION (4) -------------------- */
  {
    "slug": "plate-half-veggies",
    "name": "Make Half Your Plate Veggies",
    "domain": "nutrition",
    "category": "portion",
    "summary": "Fill about 50% of the plate with non-starchy vegetables to boost fiber and satiety.",
    "goal_type": "bool",
    "default_target": null,
    "min_viable": "Add one fist of veg to any meal.",
    "time_windows": [{ "start": "11:00", "end": "20:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Assemble the veg first when plating.",
    "equipment": "",
    "contraindications": "Adjust for GI sensitivity.",
    "difficulty": "easy",
    "estimated_minutes": 4,
    "coach_copy": null,
    "tags": "portion,vegetables,fiber,satiety",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "flaxseed-1tbsp",
    "name": "Add 1 Tbsp Ground Flaxseed",
    "domain": "nutrition",
    "category": "fiber",
    "summary": "Adds fiber and ALA omega-3s to support heart and gut health.",
    "goal_type": "count",
    "default_target": 1.0,
    "min_viable": "Sprinkle 1 teaspoon on yogurt or oatmeal.",
    "time_windows": [{ "start": "07:00", "end": "12:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Store a jar beside breakfast items.",
    "equipment": "",
    "contraindications": "Increase gradually; check meds with clinician.",
    "difficulty": "easy",
    "estimated_minutes": 1,
    "coach_copy": null,
    "tags": "flaxseed,fiber,omega-3,ALA",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "protein-lunch-30g",
    "name": "Protein at Lunch (30 g)",
    "domain": "nutrition",
    "category": "protein",
    "summary": "Anchor lunch with ~30 g protein to improve afternoon satiety and focus.",
    "goal_type": "count",
    "default_target": 30.0,
    "min_viable": "Hit at least 20 g once.",
    "time_windows": [{ "start": "11:00", "end": "14:30" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Plan protein first when ordering or prepping.",
    "equipment": "",
    "contraindications": "Adjust per clinician for kidney disease.",
    "difficulty": "easy",
    "estimated_minutes": 5,
    "coach_copy": null,
    "tags": "protein,lunch,satiety,focus",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "veg-at-lunch",
    "name": "Add Vegetables at Lunch",
    "domain": "nutrition",
    "category": "veggies-fruits",
    "summary": "Boost midday fiber and micronutrients with a simple veg serving.",
    "goal_type": "bool",
    "default_target": null,
    "min_viable": "Add one fist of any vegetable.",
    "time_windows": [{ "start": "11:00", "end": "14:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Keep frozen veg for quick microwave steam.",
    "equipment": "",
    "contraindications": "",
    "difficulty": "easy",
    "estimated_minutes": 3,
    "coach_copy": null,
    "tags": "vegetables,lunch,fiber",
    "sources": "Perplexity deep research"
  },

  /* -------------------- EXERCISE (4) -------------------- */
  {
    "slug": "jumping-jacks-60s",
    "name": "Jumping Jacks (60s)",
    "domain": "exercise",
    "category": "cardio",
    "summary": "Quick cardio burst to elevate heart rate and energy.",
    "goal_type": "duration",
    "default_target": 1.0,
    "min_viable": "Do 20 seconds or a low-impact step jack.",
    "time_windows": [{ "start": "07:00", "end": "18:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Between tasks or before a shower.",
    "equipment": "",
    "contraindications": "Choose low impact if joint pain.",
    "difficulty": "easy",
    "estimated_minutes": 1,
    "coach_copy": null,
    "tags": "cardio,energy,vo2",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "band-external-rotation-20",
    "name": "Band External Rotations (20 reps)",
    "domain": "exercise",
    "category": "strength",
    "summary": "Strengthens rotator cuff to support shoulder health and posture.",
    "goal_type": "count",
    "default_target": 20.0,
    "min_viable": "Do 8 reps with a light band per side.",
    "time_windows": [{ "start": "08:00", "end": "18:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Keep a band visible at the desk.",
    "equipment": "resistance band",
    "contraindications": "Modify for shoulder pain.",
    "difficulty": "easy",
    "estimated_minutes": 3,
    "coach_copy": null,
    "tags": "shoulder,rotator-cuff,posture,strength",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "prone-press-up-10",
    "name": "Prone Press-Ups (10 reps)",
    "domain": "exercise",
    "category": "mobility",
    "summary": "Gentle spinal extension to counter prolonged sitting.",
    "goal_type": "count",
    "default_target": 10.0,
    "min_viable": "Do 4 slow reps within comfort.",
    "time_windows": [{ "start": "10:00", "end": "18:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Add to posture breaks.",
    "equipment": "mat (optional)",
    "contraindications": "Avoid if extension-sensitive back pain.",
    "difficulty": "easy",
    "estimated_minutes": 2,
    "coach_copy": null,
    "tags": "spine,extension,desk,mobility",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "reverse-plank-30s",
    "name": "Reverse Plank (30s)",
    "domain": "exercise",
    "category": "core",
    "summary": "Opens chest and strengthens posterior chain and core.",
    "goal_type": "duration",
    "default_target": 0.5,
    "min_viable": "Hold 10 seconds with knees bent.",
    "time_windows": [{ "start": "08:00", "end": "20:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "After regular plank or before showers.",
    "equipment": "",
    "contraindications": "Modify for wrist or shoulder discomfort.",
    "difficulty": "medium",
    "estimated_minutes": 1,
    "coach_copy": null,
    "tags": "core,posterior,posture",
    "sources": "Perplexity deep research"
  },

  /* -------------------- RECOVERY (2) -------------------- */
  {
    "slug": "diaphragmatic-breathing-3",
    "name": "Diaphragmatic Breathing (3 min)",
    "domain": "recovery",
    "category": "breathwork",
    "summary": "Slow belly breathing to reduce stress and downshift the nervous system.",
    "goal_type": "duration",
    "default_target": 3.0,
    "min_viable": "Do 60 seconds hands on belly/chest.",
    "time_windows": [{ "start": "12:00", "end": "21:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Between meetings or at lights-out.",
    "equipment": "",
    "contraindications": "Stop if dizzy; breathe comfortably.",
    "difficulty": "easy",
    "estimated_minutes": 3,
    "coach_copy": null,
    "tags": "breathing,relaxation,stress",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "worry-journal-5",
    "name": "Worry Journal (5 min)",
    "domain": "recovery",
    "category": "mental-fitness",
    "summary": "Externalize concerns on paper to reduce rumination before bed.",
    "goal_type": "duration",
    "default_target": 5.0,
    "min_viable": "Write one sentence.",
    "time_windows": [{ "start": "19:30", "end": "22:30" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Do during wind-down routine.",
    "equipment": "notebook",
    "contraindications": "",
    "difficulty": "easy",
    "estimated_minutes": 5,
    "coach_copy": null,
    "tags": "journaling,rumination,sleep,stress",
    "sources": "Perplexity deep research"
  }
]
$json$::jsonb;
BEGIN
  PERFORM public.rpc_upsert_habit_templates(v_payload);
END;
$$;