-- Batch 16 — Biohacks (BH-1)
-- Adds 10 evidence-based biohack habits
-- Current wrapper: public.secure_upsert_habit_templates(jsonb)

DO $$
DECLARE
  v_payload jsonb := $json$
[
  {
    "slug": "cold-water-immersion-1min",
    "name": "Cold Water Immersion (1 min)",
    "domain": "recovery",
    "category": "cold-therapy",
    "summary": "Brief cold exposure may improve stress resilience and mood; start conservatively.",
    "goal_type": "duration",
    "default_target": 1.0,
    "min_viable": "30 seconds cool shower finish.",
    "time_windows": [{ "start": "06:30", "end": "10:00" }],
    "suggested_rules": [{ "type": "weekly", "params": {"days_per_week":3} }],
    "cues_and_stacking": "Do after morning shower or workout.",
    "equipment": "shower/tub",
    "contraindications": "Cardiovascular disease, uncontrolled hypertension, pregnancy—consult clinician. Avoid breath-holds.",
    "difficulty": "medium",
    "estimated_minutes": 1,
    "coach_copy": null,
    "tags": "cold,cold-shower,immersion,stress,alertness",
    "sources": "User-provided PDF: Evidence-Based Biohacks"
  },
  {
    "slug": "sauna-15min",
    "name": "Sauna (15 min)",
    "domain": "recovery",
    "category": "heat-therapy",
    "summary": "Passive heat may support cardiovascular conditioning and relaxation.",
    "goal_type": "duration",
    "default_target": 15.0,
    "min_viable": "8–10 min at a comfortable heat; hydrate.",
    "time_windows": [{ "start": "16:00", "end": "21:00" }],
    "suggested_rules": [{ "type": "weekly", "params": {"days_per_week":3} }],
    "cues_and_stacking": "Add post-training or evening wind-down.",
    "equipment": "sauna or hot bath",
    "contraindications": "Heat intolerance, hypotension, heart conditions—seek medical advice; hydrate and exit if dizzy.",
    "difficulty": "medium",
    "estimated_minutes": 15,
    "coach_copy": null,
    "tags": "sauna,heat,recovery,cardio,relaxation",
    "sources": "User-provided PDF: Evidence-Based Biohacks"
  },
  {
    "slug": "morning-sunlight-5min",
    "name": "Morning Sunlight (5 min)",
    "domain": "recovery",
    "category": "circadian",
    "summary": "Outdoor morning light helps anchor circadian rhythm and daytime alertness.",
    "goal_type": "duration",
    "default_target": 5.0,
    "min_viable": "2 minutes outside facing the sky.",
    "time_windows": [{ "start": "06:30", "end": "10:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Combine with short walk or coffee outside.",
    "equipment": "",
    "contraindications": "Protect skin/eyes as needed; avoid staring at sun.",
    "difficulty": "easy",
    "estimated_minutes": 5,
    "coach_copy": null,
    "tags": "light,circadian,morning,alertness",
    "sources": "User-provided PDF: Evidence-Based Biohacks"
  },
  {
    "slug": "red-light-therapy-5min",
    "name": "Red Light Therapy (5 min)",
    "domain": "recovery",
    "category": "light-therapy",
    "summary": "Low-level red/near-IR light (photobiomodulation) may aid recovery for some users.",
    "goal_type": "duration",
    "default_target": 5.0,
    "min_viable": "2 minutes at recommended distance.",
    "time_windows": [{ "start": "19:00", "end": "22:00" }],
    "suggested_rules": [{ "type": "weekly", "params": {"days_per_week":3} }],
    "cues_and_stacking": "Use during evening wind-down.",
    "equipment": "red/near-IR device",
    "contraindications": "Photosensitivity disorders or photosensitizing meds—consult clinician; avoid eye exposure per device guidance.",
    "difficulty": "easy",
    "estimated_minutes": 5,
    "coach_copy": null,
    "tags": "red-light,PBM,recovery,photobiomodulation",
    "sources": "User-provided PDF: Evidence-Based Biohacks"
  },
  {
    "slug": "creatine-monohydrate-5g",
    "name": "Creatine Monohydrate (5 g)",
    "domain": "nutrition",
    "category": "supplements",
    "summary": "Daily creatine supports high-intensity performance and may aid cognition in some contexts.",
    "goal_type": "count",
    "default_target": 5.0,
    "min_viable": "3 g mixed in water.",
    "time_windows": [{ "start": "07:00", "end": "21:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Add to a shake or post-workout.",
    "equipment": "creatine powder",
    "contraindications": "Kidney disease—use only with clinician guidance; hydrate adequately.",
    "difficulty": "easy",
    "estimated_minutes": 1,
    "coach_copy": null,
    "tags": "creatine,strength,power,cognition",
    "sources": "User-provided PDF: Evidence-Based Biohacks"
  },
  {
    "slug": "magnesium-glycinate-200mg",
    "name": "Magnesium Glycinate (200 mg)",
    "domain": "nutrition",
    "category": "supplements",
    "summary": "Evening magnesium may support relaxation and sleep quality for some people.",
    "goal_type": "count",
    "default_target": 200.0,
    "min_viable": "100 mg with a snack.",
    "time_windows": [{ "start": "20:00", "end": "23:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Take with herbal tea during wind-down.",
    "equipment": "capsules/tablets",
    "contraindications": "Check meds and kidney status with clinician; may cause GI upset at higher doses.",
    "difficulty": "easy",
    "estimated_minutes": 1,
    "coach_copy": null,
    "tags": "magnesium,sleep,relaxation,glycinate",
    "sources": "User-provided PDF: Evidence-Based Biohacks"
  },
  {
    "slug": "beetroot-nitrate-preworkout",
    "name": "Beetroot Nitrate (1 serving pre-workout)",
    "domain": "nutrition",
    "category": "ergogenic",
    "summary": "Dietary nitrates (e.g., beetroot) can modestly improve endurance in some users.",
    "goal_type": "count",
    "default_target": 1.0,
    "min_viable": "Half serving if new to nitrates.",
    "time_windows": [{ "start": "07:00", "end": "17:00" }],
    "suggested_rules": [{ "type": "weekly", "params": {"days_per_week":3} }],
    "cues_and_stacking": "Take 60–180 min before key session.",
    "equipment": "beetroot shot/chews",
    "contraindications": "Check nitrate-sensitive meds/conditions with clinician.",
    "difficulty": "easy",
    "estimated_minutes": 1,
    "coach_copy": null,
    "tags": "beetroot,nitrate,endurance,ergogenic",
    "sources": "User-provided PDF: Evidence-Based Biohacks"
  },
  {
    "slug": "dark-chocolate-70-10g",
    "name": "Dark Chocolate 70% (10 g)",
    "domain": "nutrition",
    "category": "antioxidants",
    "summary": "Cocoa flavanols may support vascular function and mood; watch added sugar.",
    "goal_type": "count",
    "default_target": 10.0,
    "min_viable": "1–2 small squares (≈5 g).",
    "time_windows": [{ "start": "12:00", "end": "20:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Use as a dessert swap.",
    "equipment": "",
    "contraindications": "Caffeine sensitive; consider evening cutoff.",
    "difficulty": "easy",
    "estimated_minutes": 1,
    "coach_copy": null,
    "tags": "cocoa,flavanols,vascular,mood",
    "sources": "User-provided PDF: Evidence-Based Biohacks"
  },
  {
    "slug": "caffeine-cutoff-8h",
    "name": "Caffeine Cutoff (≥8h before bed)",
    "domain": "recovery",
    "category": "sleep-hygiene",
    "summary": "Ending caffeine at least ~8 hours before sleep can reduce sleep disruption.",
    "goal_type": "bool",
    "default_target": null,
    "min_viable": "No caffeine after 2 PM.",
    "time_windows": [{ "start": "14:00", "end": "23:59" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Set an afternoon 'no-caffeine' reminder.",
    "equipment": "",
    "contraindications": "",
    "difficulty": "easy",
    "estimated_minutes": 0,
    "coach_copy": null,
    "tags": "caffeine,sleep,cutoff,adenosine",
    "sources": "User-provided PDF: Evidence-Based Biohacks"
  },
  {
    "slug": "tart-cherry-juice-8oz",
    "name": "Tart Cherry Juice (8 oz evening)",
    "domain": "nutrition",
    "category": "recovery-nutrition",
    "summary": "Polyphenol-rich tart cherry may help soreness and sleep for some users.",
    "goal_type": "count",
    "default_target": 8.0,
    "min_viable": "4 oz diluted with water.",
    "time_windows": [{ "start": "19:00", "end": "22:00" }],
    "suggested_rules": [{ "type": "weekly", "params": {"days_per_week":3} }],
    "cues_and_stacking": "Pair with evening wind-down.",
    "equipment": "",
    "contraindications": "Mind carbs if managing glucose; check interactions with certain meds.",
    "difficulty": "easy",
    "estimated_minutes": 2,
    "coach_copy": null,
    "tags": "tart-cherry,polyphenols,soreness,sleep",
    "sources": "User-provided PDF: Evidence-Based Biohacks"
  }
]
$json$::jsonb;
BEGIN
  PERFORM public.secure_upsert_habit_templates(v_payload);
END;
$$;