-- Batch 7 Habits (10 total)
DO $$
DECLARE
  v_payload jsonb := '[
  {
    "slug": "beans-serving-1",
    "name": "Eat 1 Serving of Beans/Lentils",
    "domain": "nutrition",
    "category": "legumes",
    "summary": "Adds fiber, protein, and minerals to support gut and metabolic health.",
    "goal_type": "count",
    "default_target": 1.0,
    "min_viable": "Add 2 tbsp beans to a meal.",
    "time_windows": [{ "start": "11:00", "end": "20:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Swap half your rice for beans.",
    "equipment": "",
    "contraindications": "Adjust for GI sensitivity.",
    "difficulty": "easy",
    "estimated_minutes": 5,
    "coach_copy": null,
    "tags": "beans,lentils,fiber,protein,legumes",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "whole-grain-swap",
    "name": "Whole-Grain Swap",
    "domain": "nutrition",
    "category": "whole-grains",
    "summary": "Replace refined grains to improve fiber and satiety.",
    "goal_type": "bool",
    "default_target": null,
    "min_viable": "Choose brown rice or quinoa once.",
    "time_windows": [{ "start": "10:00", "end": "21:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Plan the swap during meal prep.",
    "equipment": "",
    "contraindications": "",
    "difficulty": "easy",
    "estimated_minutes": 3,
    "coach_copy": null,
    "tags": "whole-grain,fiber,satiety",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "no-sugary-drink",
    "name": "Skip Sugary Drinks Today",
    "domain": "nutrition",
    "category": "sugar-reduction",
    "summary": "Lowers added sugar and reduces blood sugar spikes.",
    "goal_type": "bool",
    "default_target": null,
    "min_viable": "Swap soda for sparkling water.",
    "time_windows": [{ "start": "08:00", "end": "20:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Keep a water bottle on desk.",
    "equipment": "water bottle",
    "contraindications": "",
    "difficulty": "easy",
    "estimated_minutes": 0,
    "coach_copy": null,
    "tags": "sugar,beverages,metabolic-health",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "protein-breakfast",
    "name": "Add Protein to Breakfast",
    "domain": "nutrition",
    "category": "protein",
    "summary": "Improves satiety and energy through the morning.",
    "goal_type": "bool",
    "default_target": null,
    "min_viable": "Add eggs, yogurt, or protein shake.",
    "time_windows": [{ "start": "06:00", "end": "10:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Prep the night before.",
    "equipment": "",
    "contraindications": "Adjust for dairy or egg intolerance.",
    "difficulty": "easy",
    "estimated_minutes": 5,
    "coach_copy": null,
    "tags": "protein,breakfast,satiety",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "plank-60s",
    "name": "Plank (60s)",
    "domain": "exercise",
    "category": "core",
    "summary": "Builds core stability and supports posture.",
    "goal_type": "duration",
    "default_target": 1.0,
    "min_viable": "Hold 20 seconds on knees.",
    "time_windows": [{ "start": "08:00", "end": "20:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Before shower or workout.",
    "equipment": "mat",
    "contraindications": "Modify for wrist/low back pain.",
    "difficulty": "medium",
    "estimated_minutes": 1,
    "coach_copy": null,
    "tags": "plank,core,stability",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "wall-sit-60s",
    "name": "Wall Sit (60s)",
    "domain": "exercise",
    "category": "strength",
    "summary": "Builds leg endurance; minimal equipment.",
    "goal_type": "duration",
    "default_target": 1.0,
    "min_viable": "Hold 20 seconds partial depth.",
    "time_windows": [{ "start": "09:00", "end": "21:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "During kettle boil or TV break.",
    "equipment": "",
    "contraindications": "Modify for knee pain.",
    "difficulty": "medium",
    "estimated_minutes": 1,
    "coach_copy": null,
    "tags": "legs,endurance,strength",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "walk-steps-7000",
    "name": "Walk 7,000 Steps",
    "domain": "exercise",
    "category": "daily-activity",
    "summary": "Supports cardio-metabolic health with accessible movement.",
    "goal_type": "count",
    "default_target": 7000.0,
    "min_viable": "Add a 10-minute walk.",
    "time_windows": [{ "start": "07:00", "end": "21:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Park farther; walking calls.",
    "equipment": "tracker/phone",
    "contraindications": "Adjust for mobility limits.",
    "difficulty": "medium",
    "estimated_minutes": 60,
    "coach_copy": null,
    "tags": "steps,walking,daily-activity",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "mindfulness-3",
    "name": "Mindfulness (3 min)",
    "domain": "recovery",
    "category": "mindfulness",
    "summary": "Short practice reduces stress and improves focus.",
    "goal_type": "duration",
    "default_target": 3.0,
    "min_viable": "Do 60 seconds of breath focus.",
    "time_windows": [{ "start": "12:00", "end": "20:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Between meetings.",
    "equipment": "",
    "contraindications": "",
    "difficulty": "easy",
    "estimated_minutes": 3,
    "coach_copy": null,
    "tags": "mindfulness,stress,focus",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "bedroom-cool-65-68",
    "name": "Cool Bedroom (65–68°F)",
    "domain": "recovery",
    "category": "sleep-hygiene",
    "summary": "Supports melatonin and sleep depth.",
    "goal_type": "bool",
    "default_target": null,
    "min_viable": "Use a fan or lower HVAC a little.",
    "time_windows": [{ "start": "20:00", "end": "23:59" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Set thermostat with digital sunset.",
    "equipment": "fan/HVAC",
    "contraindications": "",
    "difficulty": "easy",
    "estimated_minutes": 1,
    "coach_copy": null,
    "tags": "sleep,temperature,circadian",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "foam-roll-5",
    "name": "Foam Rolling (5 min)",
    "domain": "recovery",
    "category": "mobility",
    "summary": "Releases tension and supports range of motion.",
    "goal_type": "duration",
    "default_target": 5.0,
    "min_viable": "Roll calves for 1 minute.",
    "time_windows": [{ "start": "17:00", "end": "21:00" }],
    "suggested_rules": [{ "type": "weekly", "params": {"days_per_week":3} }],
    "cues_and_stacking": "Before/after workouts or TV time.",
    "equipment": "foam roller",
    "contraindications": "Avoid acute injury areas.",
    "difficulty": "easy",
    "estimated_minutes": 5,
    "coach_copy": null,
    "tags": "foam-rolling,mobility,recovery",
    "sources": "Perplexity deep research"
  }
  ]'::jsonb;
BEGIN
  PERFORM public.rpc_upsert_habit_templates(v_payload);
END;
$$;