DO $$
DECLARE
  v_payload jsonb := '[
  {
    "slug": "omega-3-servings-2wk",
    "name": "Eat Omega-3 Fish Twice per Week",
    "domain": "nutrition",
    "category": "healthy-fats",
    "summary": "EPA/DHA support heart and brain health.",
    "goal_type": "count",
    "default_target": 2.0,
    "min_viable": "Add canned salmon once this week.",
    "time_windows": [{ "start": "07:00", "end": "22:00" }],
    "suggested_rules": [{ "type": "weekly", "params": {"days_per_week":2} }],
    "cues_and_stacking": "Schedule fish nights on calendar.",
    "equipment": "",
    "contraindications": "",
    "difficulty": "easy",
    "estimated_minutes": 15,
    "coach_copy": null,
    "tags": "omega-3,fish,healthy-fats",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "berries-cup",
    "name": "Eat 1 Cup of Berries",
    "domain": "nutrition",
    "category": "veggies-fruits",
    "summary": "Polyphenols for vascular and metabolic health.",
    "goal_type": "count",
    "default_target": 1.0,
    "min_viable": "Add 1/2 cup berries to breakfast.",
    "time_windows": [{ "start": "06:00", "end": "12:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Keep frozen berries in freezer.",
    "equipment": "",
    "contraindications": "",
    "difficulty": "easy",
    "estimated_minutes": 2,
    "coach_copy": null,
    "tags": "berries,fruit,polyphenols",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "meal-prep-30",
    "name": "30-Minute Meal Prep",
    "domain": "nutrition",
    "category": "prep",
    "summary": "Preps staples to make healthy choices easier.",
    "goal_type": "duration",
    "default_target": 30.0,
    "min_viable": "Chop one vegetable or cook one protein.",
    "time_windows": [{ "start": "10:00", "end": "18:00" }],
    "suggested_rules": [{ "type": "weekly", "params": {"days_per_week":2} }],
    "cues_and_stacking": "Sunday + Wednesday evenings.",
    "equipment": "knife,containers",
    "contraindications": "",
    "difficulty": "medium",
    "estimated_minutes": 30,
    "coach_copy": null,
    "tags": "prep,planning,consistency",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "standing-desk-30",
    "name": "Stand 30 Minutes Total",
    "domain": "exercise",
    "category": "daily-activity",
    "summary": "Breaks sedentary time; improves energy.",
    "goal_type": "duration",
    "default_target": 30.0,
    "min_viable": "Stand for 5 minutes once.",
    "time_windows": [{ "start": "09:00", "end": "18:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Stand for calls.",
    "equipment": "",
    "contraindications": "",
    "difficulty": "easy",
    "estimated_minutes": 30,
    "coach_copy": null,
    "tags": "standing,sedentary,energy",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "pushups-10",
    "name": "Do 10 Push-Ups",
    "domain": "exercise",
    "category": "strength",
    "summary": "Upper-body strength and bone health.",
    "goal_type": "count",
    "default_target": 10.0,
    "min_viable": "Do 3 wall push-ups.",
    "time_windows": [{ "start": "06:00", "end": "22:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "After brushing teeth.",
    "equipment": "",
    "contraindications": "Modify for shoulder pain.",
    "difficulty": "easy",
    "estimated_minutes": 3,
    "coach_copy": null,
    "tags": "pushups,strength,upper-body",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "stairs-5flights",
    "name": "Climb 5 Flights of Stairs",
    "domain": "exercise",
    "category": "cardio",
    "summary": "Quick VO2 stimulus and leg strength.",
    "goal_type": "count",
    "default_target": 5.0,
    "min_viable": "Climb 1 flight today.",
    "time_windows": [{ "start": "08:00", "end": "18:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Use stairs instead of elevator.",
    "equipment": "",
    "contraindications": "Avoid if unsafe stairs.",
    "difficulty": "easy",
    "estimated_minutes": 5,
    "coach_copy": null,
    "tags": "stairs,vo2,cardio",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "hip-opener-5",
    "name": "Hip Opener (5 min)",
    "domain": "exercise",
    "category": "mobility",
    "summary": "Counteracts sitting; reduces hip stiffness.",
    "goal_type": "duration",
    "default_target": 5.0,
    "min_viable": "Hold a 60-second lunge stretch.",
    "time_windows": [{ "start": "17:00", "end": "22:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "After commute or before dinner.",
    "equipment": "",
    "contraindications": "",
    "difficulty": "easy",
    "estimated_minutes": 5,
    "coach_copy": null,
    "tags": "hips,mobility,stretch",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "nsdr-20",
    "name": "NSDR (20 min)",
    "domain": "recovery",
    "category": "restoration",
    "summary": "Deeper session for recovery and focus.",
    "goal_type": "duration",
    "default_target": 20.0,
    "min_viable": "Do 3 minutes guided breathing.",
    "time_windows": [{ "start": "12:00", "end": "18:00" }],
    "suggested_rules": [{ "type": "weekly", "params": {"days_per_week":3} }],
    "cues_and_stacking": "Calendar block after lunch.",
    "equipment": "",
    "contraindications": "",
    "difficulty": "easy",
    "estimated_minutes": 20,
    "coach_copy": null,
    "tags": "nsdr,recovery,focus",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "room-darkening",
    "name": "Darken Bedroom at Night",
    "domain": "recovery",
    "category": "sleep-hygiene",
    "summary": "Improves melatonin and sleep depth.",
    "goal_type": "bool",
    "default_target": null,
    "min_viable": "Cover one LED/light source.",
    "time_windows": [{ "start": "20:00", "end": "23:59" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Use blackout curtains or mask.",
    "equipment": "sleep mask",
    "contraindications": "",
    "difficulty": "easy",
    "estimated_minutes": 3,
    "coach_copy": null,
    "tags": "sleep,dark,melatonin",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "evening-walk-10",
    "name": "Evening Walk (10 min)",
    "domain": "recovery",
    "category": "wind-down",
    "summary": "Assists digestion and sleep onset.",
    "goal_type": "duration",
    "default_target": 10.0,
    "min_viable": "Walk 3 minutes after dinner.",
    "time_windows": [{ "start": "19:00", "end": "22:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Go right after dishes.",
    "equipment": "",
    "contraindications": "",
    "difficulty": "easy",
    "estimated_minutes": 10,
    "coach_copy": null,
    "tags": "walk,digestion,sleep",
    "sources": "Perplexity deep research"
  }
  ]'::jsonb;
BEGIN
  PERFORM public.rpc_upsert_habit_templates(v_payload);
END;
$$;