-- Insert recovery-specific public challenges
INSERT INTO public_challenges (
  title, 
  description, 
  goal_description, 
  duration_days, 
  challenge_type, 
  difficulty_level, 
  category, 
  target_metric, 
  target_value, 
  target_unit, 
  badge_icon, 
  is_trending, 
  is_new, 
  participant_count,
  is_active
) VALUES 
-- Meditation Challenges
(
  '🧘‍♀️ 7-Day Meditation Streak', 
  'Build a consistent meditation practice', 
  'Complete 7 consecutive days of meditation (minimum 5 minutes each)', 
  7, 
  'streak', 
  'beginner', 
  'meditation', 
  'meditation_sessions', 
  7, 
  'sessions', 
  '🧘‍♀️', 
  true, 
  true, 
  47,
  true
),
(
  '🧘‍♂️ 21-Day Mindfulness Master', 
  'Deep dive into mindfulness practice', 
  'Meditate daily for 21 days (minimum 10 minutes each)', 
  21, 
  'habit', 
  'intermediate', 
  'meditation', 
  'meditation_minutes', 
  210, 
  'minutes', 
  '🧘‍♂️', 
  false, 
  false, 
  23,
  true
),

-- Breathing Challenges
(
  '🌬️ Breathwork Blitz', 
  'Master the art of conscious breathing', 
  'Complete 5 breathwork sessions this week', 
  7, 
  'target', 
  'beginner', 
  'breathing', 
  'breathing_sessions', 
  5, 
  'sessions', 
  '🌬️', 
  true, 
  false, 
  34,
  true
),
(
  '🫁 30-Day Breath Journey', 
  'Transform your breathing patterns', 
  'Practice breathwork for 30 consecutive days (minimum 5 minutes)', 
  30, 
  'streak', 
  'advanced', 
  'breathing', 
  'breathing_sessions', 
  30, 
  'sessions', 
  '🫁', 
  false, 
  true, 
  18,
  true
),

-- Yoga Challenges
(
  '🧘‍♀️ Yoga Flow Week', 
  'Discover the power of daily yoga', 
  'Complete 7 yoga sessions in 7 days', 
  7, 
  'streak', 
  'beginner', 
  'yoga', 
  'yoga_sessions', 
  7, 
  'sessions', 
  '🧘‍♀️', 
  true, 
  true, 
  56,
  true
),
(
  '🕉️ 21-Day Yoga Transformation', 
  'Build strength, flexibility, and inner peace', 
  'Practice yoga for 21 consecutive days (minimum 15 minutes)', 
  21, 
  'habit', 
  'intermediate', 
  'yoga', 
  'yoga_minutes', 
  315, 
  'minutes', 
  '🕉️', 
  false, 
  false, 
  29,
  true
),

-- Sleep Challenges
(
  '😴 Better Sleep Week', 
  'Optimize your sleep quality', 
  'Log 7 nights of quality sleep (7+ hours each)', 
  7, 
  'streak', 
  'beginner', 
  'sleep', 
  'sleep_sessions', 
  7, 
  'sessions', 
  '😴', 
  true, 
  false, 
  41,
  true
),
(
  '🌙 30-Day Sleep Mastery', 
  'Transform your sleep habits', 
  'Maintain consistent sleep schedule for 30 days', 
  30, 
  'habit', 
  'intermediate', 
  'sleep', 
  'sleep_hours', 
  210, 
  'hours', 
  '🌙', 
  false, 
  true, 
  25,
  true
),

-- Thermotherapy Challenges
(
  '🔥 Sauna Sprint', 
  'Experience the benefits of heat therapy', 
  'Complete 3 sauna sessions this week (minimum 15 minutes each)', 
  7, 
  'target', 
  'beginner', 
  'thermotherapy', 
  'thermotherapy_sessions', 
  3, 
  'sessions', 
  '🔥', 
  false, 
  true, 
  12,
  true
),
(
  '🧊 Cold Exposure Challenge', 
  'Build resilience through cold therapy', 
  'Complete 14 days of cold exposure (cold showers/ice baths)', 
  14, 
  'streak', 
  'advanced', 
  'thermotherapy', 
  'cold_exposure_sessions', 
  14, 
  'sessions', 
  '🧊', 
  true, 
  false, 
  31,
  true
),

-- Mixed Recovery Challenges
(
  '🌿 Recovery Warrior', 
  'Master all aspects of recovery', 
  'Complete 2 meditation, 2 breathing, and 2 yoga sessions this week', 
  7, 
  'target', 
  'intermediate', 
  'recovery', 
  'recovery_sessions', 
  6, 
  'sessions', 
  '🌿', 
  true, 
  true, 
  38,
  true
),
(
  '🧘‍♂️ Zen Master Quest', 
  'Achieve ultimate mindfulness', 
  'Complete 30 days of mixed recovery practices (meditation, yoga, breathing)', 
  30, 
  'habit', 
  'advanced', 
  'recovery', 
  'total_recovery_minutes', 
  450, 
  'minutes', 
  '🧘‍♂️', 
  false, 
  false, 
  16,
  true
);