-- Batch 6 Habits (10 total)
DO $$
DECLARE
  v_payload jsonb := '[
  {
    "slug": "leafy-greens-cup",
    "name": "Eat 1 Cup of Leafy Greens",
    "domain": "nutrition",
    "category": "veggies-fruits",
    "summary": "Rich in folate, vitamin K, and nitrates for vascular health.",
    "goal_type": "count",
    "default_target": 1.0,
    "min_viable": "Add a handful of spinach to any meal.",
    "time_windows": [{ "start": "11:00", "end": "20:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Pair with lunch or dinner.",
    "equipment": "",
    "contraindications": "",
    "difficulty": "easy",
    "estimated_minutes": 3,
    "coach_copy": null,
    "tags": "greens,spinach,kale,nutrition",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "handful-nuts",
    "name": "Eat a Handful of Nuts",
    "domain": "nutrition",
    "category": "healthy-fats",
    "summary": "Supports satiety and heart health with healthy fats.",
    "goal_type": "count",
    "default_target": 1.0,
    "min_viable": "Add a few almonds as snack.",
    "time_windows": [{ "start": "12:00", "end": "18:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Replace chips with nuts.",
    "equipment": "",
    "contraindications": "Allergy caution.",
    "difficulty": "easy",
    "estimated_minutes": 2,
    "coach_copy": null,
    "tags": "nuts,protein,healthy-fats",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "fiber-25g",
    "name": "Reach 25g Fiber",
    "domain": "nutrition",
    "category": "fiber",
    "summary": "Improves digestion, satiety, and glycemic control.",
    "goal_type": "count",
    "default_target": 25.0,
    "min_viable": "Add one serving of beans or lentils.",
    "time_windows": [{ "start": "07:00", "end": "22:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Track fiber-rich foods daily.",
    "equipment": "",
    "contraindications": "Adjust for IBS if needed.",
    "difficulty": "medium",
    "estimated_minutes": 5,
    "coach_copy": null,
    "tags": "fiber,digestion,satiety",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "calf-raises-20",
    "name": "Do 20 Calf Raises",
    "domain": "exercise",
    "category": "strength",
    "summary": "Improves ankle stability and circulation.",
    "goal_type": "count",
    "default_target": 20.0,
    "min_viable": "Do 5 reps holding a chair.",
    "time_windows": [{ "start": "09:00", "end": "21:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "During teeth brushing.",
    "equipment": "",
    "contraindications": "Avoid if Achilles injury.",
    "difficulty": "easy",
    "estimated_minutes": 3,
    "coach_copy": null,
    "tags": "calves,strength,balance",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "posture-reset-1",
    "name": "Posture Reset (1 min)",
    "domain": "exercise",
    "category": "mobility",
    "summary": "Relieves neck/back strain from sitting.",
    "goal_type": "duration",
    "default_target": 1.0,
    "min_viable": "Do one shoulder roll cycle.",
    "time_windows": [{ "start": "08:00", "end": "18:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Every 2 hours at desk.",
    "equipment": "",
    "contraindications": "",
    "difficulty": "easy",
    "estimated_minutes": 1,
    "coach_copy": null,
    "tags": "posture,desk,mobility",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "micro-hiit-3min",
    "name": "Micro HIIT (3 min)",
    "domain": "exercise",
    "category": "cardio",
    "summary": "Elevates heart rate and improves VO2 max in short burst.",
    "goal_type": "duration",
    "default_target": 3.0,
    "min_viable": "Do 30 seconds fast jumping jacks.",
    "time_windows": [{ "start": "07:00", "end": "19:00" }],
    "suggested_rules": [{ "type": "weekly", "params": {"days_per_week":3} }],
    "cues_and_stacking": "Between tasks or breaks.",
    "equipment": "",
    "contraindications": "Modify if heart issues.",
    "difficulty": "medium",
    "estimated_minutes": 3,
    "coach_copy": null,
    "tags": "hiit,cardio,energy",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "mobility-flow-10",
    "name": "Mobility Flow (10 min)",
    "domain": "recovery",
    "category": "mobility",
    "summary": "Combines stretches to keep joints healthy.",
    "goal_type": "duration",
    "default_target": 10.0,
    "min_viable": "Do 2 minutes of cat-cow or spinal twists.",
    "time_windows": [{ "start": "17:00", "end": "21:00" }],
    "suggested_rules": [{ "type": "weekly", "params": {"days_per_week":3} }],
    "cues_and_stacking": "Before or after workouts.",
    "equipment": "mat",
    "contraindications": "",
    "difficulty": "medium",
    "estimated_minutes": 10,
    "coach_copy": null,
    "tags": "mobility,stretch,joints",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "gratitude-voice-1",
    "name": "Record Gratitude Voice Note",
    "domain": "recovery",
    "category": "mindset",
    "summary": "Voice reflection reinforces positivity.",
    "goal_type": "bool",
    "default_target": null,
    "min_viable": "Say one thing aloud you appreciate.",
    "time_windows": [{ "start": "20:00", "end": "23:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Do before bed.",
    "equipment": "phone",
    "contraindications": "",
    "difficulty": "easy",
    "estimated_minutes": 2,
    "coach_copy": null,
    "tags": "gratitude,voice,positivity",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "consistent-wake-7",
    "name": "Consistent Wake Time (±30m)",
    "domain": "recovery",
    "category": "sleep-hygiene",
    "summary": "Strengthens circadian rhythm and sleep quality.",
    "goal_type": "bool",
    "default_target": null,
    "min_viable": "Keep wake time within 1 hour range.",
    "time_windows": [{ "start": "05:00", "end": "09:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Set consistent alarm.",
    "equipment": "alarm clock",
    "contraindications": "",
    "difficulty": "medium",
    "estimated_minutes": 0,
    "coach_copy": null,
    "tags": "sleep,circadian,consistency",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "blue-light-filter",
    "name": "Use Blue-Light Filter After Sunset",
    "domain": "recovery",
    "category": "sleep-hygiene",
    "summary": "Reduces evening light disruption of melatonin.",
    "goal_type": "bool",
    "default_target": null,
    "min_viable": "Enable Night Shift or f.lux.",
    "time_windows": [{ "start": "19:00", "end": "23:59" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Turn on filter with lights.",
    "equipment": "phone/computer",
    "contraindications": "",
    "difficulty": "easy",
    "estimated_minutes": 0,
    "coach_copy": null,
    "tags": "blue-light,sleep,screen",
    "sources": "Perplexity deep research"
  }
  ]'::jsonb;
BEGIN
  PERFORM public.rpc_upsert_habit_templates(v_payload);
END;
$$;