-- Batch 8 Habits (10 total)
DO $$
DECLARE
  v_payload jsonb := '[
  {
    "slug": "fermented-food-1",
    "name": "Eat 1 Fermented Food",
    "domain": "nutrition",
    "category": "gut-health",
    "summary": "Supports a healthy microbiome with beneficial bacteria.",
    "goal_type": "count",
    "default_target": 1.0,
    "min_viable": "Add a spoon of yogurt/kimchi.",
    "time_windows": [{ "start": "11:00", "end": "20:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Top bowls/salads with kefir or sauerkraut.",
    "equipment": "",
    "contraindications": "Watch sodium for kimchi/sauerkraut.",
    "difficulty": "easy",
    "estimated_minutes": 2,
    "coach_copy": null,
    "tags": "fermented,yogurt,kefir,kimchi,gut",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "olive-oil-swap",
    "name": "Olive-Oil Swap",
    "domain": "nutrition",
    "category": "healthy-fats",
    "summary": "Replace refined oils with extra-virgin olive oil for heart health.",
    "goal_type": "bool",
    "default_target": null,
    "min_viable": "Use olive oil for one meal today.",
    "time_windows": [{ "start": "10:00", "end": "21:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Keep a bottle on the counter.",
    "equipment": "",
    "contraindications": "",
    "difficulty": "easy",
    "estimated_minutes": 1,
    "coach_copy": null,
    "tags": "olive-oil,healthy-fats,swap",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "glute-bridges-20",
    "name": "Do 20 Glute Bridges",
    "domain": "exercise",
    "category": "strength",
    "summary": "Activates posterior chain and supports low-back health.",
    "goal_type": "count",
    "default_target": 20.0,
    "min_viable": "Do 8 reps with control.",
    "time_windows": [{ "start": "07:00", "end": "21:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Add after warm-up.",
    "equipment": "mat",
    "contraindications": "Modify for back discomfort.",
    "difficulty": "easy",
    "estimated_minutes": 4,
    "coach_copy": null,
    "tags": "glutes,posterior,strength",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "single-leg-balance-60s",
    "name": "Single-Leg Balance (60s total)",
    "domain": "exercise",
    "category": "balance",
    "summary": "Improves proprioception and ankle stability.",
    "goal_type": "duration",
    "default_target": 1.0,
    "min_viable": "Balance 15s per side holding support.",
    "time_windows": [{ "start": "09:00", "end": "19:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Do while brushing teeth.",
    "equipment": "",
    "contraindications": "Use support if dizzy/unstable.",
    "difficulty": "easy",
    "estimated_minutes": 1,
    "coach_copy": null,
    "tags": "balance,ankle,stability",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "post-meal-walk-10",
    "name": "Post-Meal Walk (10 min)",
    "domain": "exercise",
    "category": "daily-activity",
    "summary": "Helps glucose control and aids digestion.",
    "goal_type": "duration",
    "default_target": 10.0,
    "min_viable": "Walk 3 minutes after one meal.",
    "time_windows": [{ "start": "12:00", "end": "21:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Walk right after dishes.",
    "equipment": "",
    "contraindications": "",
    "difficulty": "easy",
    "estimated_minutes": 10,
    "coach_copy": null,
    "tags": "walk,glucose,digestion",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "band-pull-aparts-30",
    "name": "Band Pull-Aparts (30 reps)",
    "domain": "exercise",
    "category": "strength",
    "summary": "Strengthens upper back; counters rounded shoulders.",
    "goal_type": "count",
    "default_target": 30.0,
    "min_viable": "Do 10 reps with light band.",
    "time_windows": [{ "start": "08:00", "end": "18:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Keep band at desk.",
    "equipment": "resistance band",
    "contraindications": "Modify for shoulder pain.",
    "difficulty": "easy",
    "estimated_minutes": 3,
    "coach_copy": null,
    "tags": "upper-back,posture,strength",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "breathing-4-7-8-2",
    "name": "4-7-8 Breathing (2 min)",
    "domain": "recovery",
    "category": "breathwork",
    "summary": "Activates parasympathetic response and calms the mind.",
    "goal_type": "duration",
    "default_target": 2.0,
    "min_viable": "Do two full 4-7-8 cycles.",
    "time_windows": [{ "start": "19:00", "end": "23:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Use at lights-out.",
    "equipment": "",
    "contraindications": "",
    "difficulty": "easy",
    "estimated_minutes": 2,
    "coach_copy": null,
    "tags": "breathing,relaxation,sleep",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "consistent-bedtime-30",
    "name": "Consistent Bedtime (±30m)",
    "domain": "recovery",
    "category": "sleep-hygiene",
    "summary": "Stabilizes circadian rhythm and improves sleep quality.",
    "goal_type": "bool",
    "default_target": null,
    "min_viable": "Keep bedtime within 1 hour range.",
    "time_windows": [{ "start": "20:00", "end": "23:59" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Evening alarm + digital sunset.",
    "equipment": "",
    "contraindications": "",
    "difficulty": "medium",
    "estimated_minutes": 0,
    "coach_copy": null,
    "tags": "sleep,circadian,consistency",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "progressive-relaxation-5",
    "name": "Progressive Relaxation (5 min)",
    "domain": "recovery",
    "category": "relaxation",
    "summary": "Reduces muscle tension through contract–release cycles.",
    "goal_type": "duration",
    "default_target": 5.0,
    "min_viable": "Relax face/shoulders only.",
    "time_windows": [{ "start": "19:00", "end": "22:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Pair with evening routine.",
    "equipment": "",
    "contraindications": "Avoid painful areas.",
    "difficulty": "easy",
    "estimated_minutes": 5,
    "coach_copy": null,
    "tags": "relaxation,stress,sleep",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "hot-bath-10",
    "name": "Warm Bath/Soak (10 min)",
    "domain": "recovery",
    "category": "heat-therapy",
    "summary": "Promotes relaxation and supports sleep onset latency.",
    "goal_type": "duration",
    "default_target": 10.0,
    "min_viable": "Soak hands/feet in warm water.",
    "time_windows": [{ "start": "19:00", "end": "22:00" }],
    "suggested_rules": [{ "type": "weekly", "params": {"days_per_week":2} }],
    "cues_and_stacking": "Schedule on high-stress days.",
    "equipment": "tub/basin",
    "contraindications": "Caution with heat sensitivity or certain CV conditions.",
    "difficulty": "easy",
    "estimated_minutes": 10,
    "coach_copy": null,
    "tags": "heat,bath,relaxation,sleep",
    "sources": "Perplexity deep research"
  }
  ]'::jsonb;
BEGIN
  PERFORM public.rpc_upsert_habit_templates(v_payload);
END;
$$;