-- Batch 18 — Biohacks (BH-3)
-- Adds 10 evidence-based biohack habits
-- Using internal rpc_upsert_habit_templates for migrations
-- Expected totals after: Total 183 (N62 / E57 / R64)

DO $$
DECLARE
  v_payload jsonb := $json$
[
  {
    "slug": "ruck-walk-10",
    "name": "Ruck Walk (10 min)",
    "domain": "exercise",
    "category": "cardio",
    "summary": "Walk with a light pack to increase load and energy expenditure.",
    "goal_type": "duration",
    "default_target": 10.0,
    "min_viable": "3 minutes with very light load.",
    "time_windows": [{ "start": "07:00", "end": "18:00" }],
    "suggested_rules": [{ "type": "weekly", "params": {"days_per_week":3} }],
    "cues_and_stacking": "Use a backpack on a coffee walk.",
    "equipment": "backpack",
    "contraindications": "Back or joint pain—start unloaded and progress.",
    "difficulty": "easy",
    "estimated_minutes": 10,
    "coach_copy": null,
    "tags": "ruck,loaded-walk,cardio",
    "sources": "User-provided PDF: Evidence-Based Biohacks"
  },
  {
    "slug": "zone2-cardio-20",
    "name": "Zone 2 Cardio (20 min)",
    "domain": "exercise",
    "category": "cardio",
    "summary": "Steady easy pace where you can talk in full sentences.",
    "goal_type": "duration",
    "default_target": 20.0,
    "min_viable": "8 minutes continuous.",
    "time_windows": [{ "start": "07:00", "end": "18:00" }],
    "suggested_rules": [{ "type": "weekly", "params": {"days_per_week":3} }],
    "cues_and_stacking": "Add to lunch break walks.",
    "equipment": "",
    "contraindications": "As per clinician for cardiac conditions.",
    "difficulty": "easy",
    "estimated_minutes": 20,
    "coach_copy": null,
    "tags": "aerobic,zone2,endurance",
    "sources": "User-provided PDF: Evidence-Based Biohacks"
  },
  {
    "slug": "sprint-20s-x6",
    "name": "Sprint Intervals (6 x 20s)",
    "domain": "exercise",
    "category": "cardio",
    "summary": "Short hard efforts with full recovery to boost power and VO2.",
    "goal_type": "count",
    "default_target": 6.0,
    "min_viable": "Do 2 to 3 gentle accelerations.",
    "time_windows": [{ "start": "08:00", "end": "17:00" }],
    "suggested_rules": [{ "type": "weekly", "params": {"days_per_week":2} }],
    "cues_and_stacking": "Warm up 5 minutes first.",
    "equipment": "",
    "contraindications": "Avoid if acute injury; progress cautiously.",
    "difficulty": "hard",
    "estimated_minutes": 12,
    "coach_copy": null,
    "tags": "sprint,intervals,hiit",
    "sources": "User-provided PDF: Evidence-Based Biohacks"
  },
  {
    "slug": "jump-rope-60s",
    "name": "Jump Rope (60s)",
    "domain": "exercise",
    "category": "cardio",
    "summary": "Quick cardio burst; great coordination and bone-loading stimulus.",
    "goal_type": "duration",
    "default_target": 1.0,
    "min_viable": "20 seconds or shadow jumps.",
    "time_windows": [{ "start": "07:00", "end": "18:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Between tasks or before a shower.",
    "equipment": "jump rope (optional)",
    "contraindications": "Low impact alternative if joint pain.",
    "difficulty": "medium",
    "estimated_minutes": 1,
    "coach_copy": null,
    "tags": "cardio,plyo,bone",
    "sources": "User-provided PDF: Evidence-Based Biohacks"
  },
  {
    "slug": "calf-raises-30",
    "name": "Calf Raises (30 reps)",
    "domain": "exercise",
    "category": "strength",
    "summary": "Simple lower-leg strength and tendon capacity work.",
    "goal_type": "count",
    "default_target": 30.0,
    "min_viable": "Do 10 reps with support.",
    "time_windows": [{ "start": "08:00", "end": "20:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Do while brushing teeth.",
    "equipment": "",
    "contraindications": "Modify if Achilles pain.",
    "difficulty": "easy",
    "estimated_minutes": 3,
    "coach_copy": null,
    "tags": "calf,ankle,tendon,strength",
    "sources": "User-provided PDF: Evidence-Based Biohacks"
  },
  {
    "slug": "wall-sit-45s",
    "name": "Wall Sit (45s)",
    "domain": "exercise",
    "category": "strength",
    "summary": "Isometric hold for quads and trunk.",
    "goal_type": "duration",
    "default_target": 0.75,
    "min_viable": "15 seconds at higher seat height.",
    "time_windows": [{ "start": "08:00", "end": "20:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Add after a walk.",
    "equipment": "",
    "contraindications": "Adjust knee angle for comfort.",
    "difficulty": "medium",
    "estimated_minutes": 1,
    "coach_copy": null,
    "tags": "quads,isometric,strength",
    "sources": "User-provided PDF: Evidence-Based Biohacks"
  },
  {
    "slug": "green-tea-1cup",
    "name": "Green Tea (1 cup)",
    "domain": "nutrition",
    "category": "antioxidants",
    "summary": "Polyphenol-rich beverage that may support vascular and cognitive health.",
    "goal_type": "count",
    "default_target": 1.0,
    "min_viable": "Half cup warm tea.",
    "time_windows": [{ "start": "09:00", "end": "16:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Swap for afternoon coffee.",
    "equipment": "kettle/mug",
    "contraindications": "Caffeine sensitivity; consider earlier cutoff.",
    "difficulty": "easy",
    "estimated_minutes": 5,
    "coach_copy": null,
    "tags": "green-tea,polyphenols,EGCG",
    "sources": "User-provided PDF: Evidence-Based Biohacks"
  },
  {
    "slug": "collagen-peptides-10g",
    "name": "Collagen Peptides (10 g)",
    "domain": "nutrition",
    "category": "supplements",
    "summary": "Collagen with vitamin C may support joint and tendon health.",
    "goal_type": "count",
    "default_target": 10.0,
    "min_viable": "5 g mixed in water.",
    "time_windows": [{ "start": "07:00", "end": "18:00" }],
    "suggested_rules": [{ "type": "weekly", "params": {"days_per_week":5} }],
    "cues_and_stacking": "Take 30 to 60 minutes before training.",
    "equipment": "powder",
    "contraindications": "Check allergens; not a complete protein.",
    "difficulty": "easy",
    "estimated_minutes": 1,
    "coach_copy": null,
    "tags": "collagen,tendon,joint,vitamin-c",
    "sources": "User-provided PDF: Evidence-Based Biohacks"
  },
  {
    "slug": "contrast-shower-3",
    "name": "Contrast Shower (3 cycles)",
    "domain": "recovery",
    "category": "hot-cold",
    "summary": "Alternate warm and cool water to promote alertness and perceived recovery.",
    "goal_type": "count",
    "default_target": 3.0,
    "min_viable": "1 warm then cool cycle.",
    "time_windows": [{ "start": "07:00", "end": "10:00" }],
    "suggested_rules": [{ "type": "weekly", "params": {"days_per_week":3} }],
    "cues_and_stacking": "Finish a normal shower with cycles.",
    "equipment": "shower",
    "contraindications": "Cardiovascular conditions or pregnancy—consult clinician.",
    "difficulty": "medium",
    "estimated_minutes": 5,
    "coach_copy": null,
    "tags": "contrast,hot-cold,alertness,recovery",
    "sources": "User-provided PDF: Evidence-Based Biohacks"
  },
  {
    "slug": "midday-outdoor-break-10",
    "name": "Midday Outdoor Break (10 min)",
    "domain": "recovery",
    "category": "circadian",
    "summary": "Daylight exposure boosts mood and helps anchor circadian signals.",
    "goal_type": "duration",
    "default_target": 10.0,
    "min_viable": "3 minutes outside.",
    "time_windows": [{ "start": "11:30", "end": "15:30" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Walk a loop after lunch.",
    "equipment": "",
    "contraindications": "Sun protection as needed.",
    "difficulty": "easy",
    "estimated_minutes": 10,
    "coach_copy": null,
    "tags": "light,daylight,circadian,mood",
    "sources": "User-provided PDF: Evidence-Based Biohacks"
  }
]
$json$::jsonb;
BEGIN
  PERFORM public.rpc_upsert_habit_templates(v_payload);
END;
$$;