-- Batch 3: Import 10 more habit templates (recovery & lifestyle focus)
DO $$
DECLARE
  v_payload jsonb := '[
  {
    "slug": "hamstring-stretch-5",
    "name": "Hamstring Stretch (5 min)",
    "domain": "exercise",
    "category": "mobility",
    "summary": "Eases tightness and supports low-back health.",
    "goal_type": "duration",
    "default_target": 5.0,
    "min_viable": "Stretch for 60 seconds.",
    "time_windows": [{ "start": "06:00", "end": "22:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "After sitting >60 minutes.",
    "equipment": "",
    "contraindications": "",
    "difficulty": "easy",
    "estimated_minutes": 5,
    "coach_copy": null,
    "tags": "stretch,hamstrings,mobility",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "morning-sunlight-10",
    "name": "Get Morning Sunlight (10 min)",
    "domain": "recovery",
    "category": "circadian",
    "summary": "Sets circadian rhythm; improves sleep and mood.",
    "goal_type": "duration",
    "default_target": 10.0,
    "min_viable": "Step outside for 2 minutes.",
    "time_windows": [{ "start": "06:30", "end": "10:30" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Combine with morning walk or coffee.",
    "equipment": "",
    "contraindications": "",
    "difficulty": "easy",
    "estimated_minutes": 10,
    "coach_copy": null,
    "tags": "sunlight,circadian,sleep",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "no-caffeine-after-2pm",
    "name": "No Caffeine After 2 PM",
    "domain": "recovery",
    "category": "sleep-hygiene",
    "summary": "Improves sleep quality and latency.",
    "goal_type": "bool",
    "default_target": null,
    "min_viable": "Swap afternoon coffee for herbal tea.",
    "time_windows": [{ "start": "14:00", "end": "23:59" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Set an '\''off-caffeine'\'' calendar alert.",
    "equipment": "",
    "contraindications": "",
    "difficulty": "easy",
    "estimated_minutes": 0,
    "coach_copy": null,
    "tags": "caffeine,sleep,latency",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "journaling-5",
    "name": "Journaling (5 min)",
    "domain": "recovery",
    "category": "mental-fitness",
    "summary": "Reduces stress and clarifies priorities.",
    "goal_type": "duration",
    "default_target": 5.0,
    "min_viable": "Write one sentence.",
    "time_windows": [{ "start": "06:00", "end": "22:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Pair with morning coffee or bedtime.",
    "equipment": "notebook",
    "contraindications": "",
    "difficulty": "easy",
    "estimated_minutes": 5,
    "coach_copy": null,
    "tags": "journaling,clarity,stress",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "gratitude-3",
    "name": "List 3 Gratitudes",
    "domain": "recovery",
    "category": "mindset",
    "summary": "Improves mood and resilience.",
    "goal_type": "count",
    "default_target": 3.0,
    "min_viable": "Write down one thing you appreciate.",
    "time_windows": [{ "start": "06:00", "end": "22:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Do it at dinner or bedtime.",
    "equipment": "",
    "contraindications": "",
    "difficulty": "easy",
    "estimated_minutes": 3,
    "coach_copy": null,
    "tags": "gratitude,positivity,mental-health",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "box-breathing-5",
    "name": "Box Breathing (5 min)",
    "domain": "recovery",
    "category": "breathwork",
    "summary": "Downshifts the nervous system; improves focus.",
    "goal_type": "duration",
    "default_target": 5.0,
    "min_viable": "Do 1 minute of 4-4-4-4 breathing.",
    "time_windows": [{ "start": "08:00", "end": "20:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Use before stressful calls or workouts.",
    "equipment": "",
    "contraindications": "",
    "difficulty": "easy",
    "estimated_minutes": 5,
    "coach_copy": null,
    "tags": "breathing,calm,focus",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "cold-shower-1",
    "name": "Cold Shower (30–60s)",
    "domain": "recovery",
    "category": "cold-therapy",
    "summary": "Acute alertness and resilience training.",
    "goal_type": "duration",
    "default_target": 1.0,
    "min_viable": "Finish warm shower with 15s cold.",
    "time_windows": [{ "start": "06:00", "end": "12:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Pair with morning routine.",
    "equipment": "",
    "contraindications": "Avoid with certain cardiovascular conditions.",
    "difficulty": "medium",
    "estimated_minutes": 1,
    "coach_copy": null,
    "tags": "cold,shower,alertness",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "digital-sunset-60",
    "name": "Digital Sunset (60 min pre-bed)",
    "domain": "recovery",
    "category": "sleep-hygiene",
    "summary": "Reduces blue light and mental stimulation before sleep.",
    "goal_type": "bool",
    "default_target": null,
    "min_viable": "Power down 15 minutes earlier than usual.",
    "time_windows": [{ "start": "20:30", "end": "23:59" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Use a bedtime reminder and warm lights.",
    "equipment": "",
    "contraindications": "",
    "difficulty": "medium",
    "estimated_minutes": 0,
    "coach_copy": null,
    "tags": "screen,blue-light,sleep",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "tidy-10",
    "name": "10-Minute Tidy",
    "domain": "lifestyle",
    "category": "environment",
    "summary": "Lower clutter to reduce stress and friction.",
    "goal_type": "duration",
    "default_target": 10.0,
    "min_viable": "Tidy one surface.",
    "time_windows": [{ "start": "18:00", "end": "21:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "After dinner; before TV.",
    "equipment": "",
    "contraindications": "",
    "difficulty": "easy",
    "estimated_minutes": 10,
    "coach_copy": null,
    "tags": "tidy,environment,stress",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "budget-check",
    "name": "Daily Budget Check (2 min)",
    "domain": "lifestyle",
    "category": "finance",
    "summary": "Quick look to improve awareness and reduce anxiety.",
    "goal_type": "duration",
    "default_target": 2.0,
    "min_viable": "Open your spending app once.",
    "time_windows": [{ "start": "18:00", "end": "22:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Pair with evening routine.",
    "equipment": "phone",
    "contraindications": "",
    "difficulty": "easy",
    "estimated_minutes": 2,
    "coach_copy": null,
    "tags": "finance,awareness,stress",
    "sources": "Perplexity deep research"
  }
  ]'::jsonb;
BEGIN
  PERFORM public.rpc_upsert_habit_templates(v_payload);
END;
$$;