-- Batch 17 — Biohacks (BH-2)
-- Adds 10 evidence-based biohack habits
-- Using internal rpc_upsert_habit_templates for migrations
-- Expected totals after apply: Total 173 (Nutrition 60, Exercise 51, Recovery 62)

DO $$
DECLARE
  v_payload jsonb := $json$
[
  {
    "slug": "blue-light-glasses-90",
    "name": "Blue-Light Glasses (90 min pre-bed)",
    "domain": "recovery",
    "category": "sleep-hygiene",
    "summary": "Wear blue-light blocking glasses in the last 60-90 minutes before bed to reduce light-driven alerting.",
    "goal_type": "duration",
    "default_target": 90.0,
    "min_viable": "Use for at least 30 minutes tonight.",
    "time_windows": [{ "start": "19:00", "end": "23:30" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Put glasses by the couch or nightstand.",
    "equipment": "blue-light blocking glasses",
    "contraindications": "None specific; remove if eye strain.",
    "difficulty": "easy",
    "estimated_minutes": 1,
    "coach_copy": null,
    "tags": "blue-light,sleep,evening,glasses",
    "sources": "User-provided PDF: Evidence-Based Biohacks"
  },
  {
    "slug": "mouth-taping-trial",
    "name": "Mouth Taping Trial (sleep)",
    "domain": "recovery",
    "category": "sleep-hygiene",
    "summary": "Encourage nasal breathing during sleep using dedicated mouth tape.",
    "goal_type": "bool",
    "default_target": null,
    "min_viable": "Test for 5 minutes pre-sleep while reading.",
    "time_windows": [{ "start": "20:30", "end": "23:59" }],
    "suggested_rules": [{ "type": "weekly", "params": { "days_per_week": 3 } }],
    "cues_and_stacking": "Keep tape with your eye mask and earplugs.",
    "equipment": "sleep mouth tape",
    "contraindications": "Do not use with suspected sleep apnea, nasal obstruction, respiratory or cardiac conditions; consult a clinician.",
    "difficulty": "easy",
    "estimated_minutes": 1,
    "coach_copy": null,
    "tags": "nasal-breathing,sleep,mouth-tape",
    "sources": "User-provided PDF: Evidence-Based Biohacks"
  },
  {
    "slug": "nasal-strips-night",
    "name": "Nasal Strips at Night",
    "domain": "recovery",
    "category": "breathing",
    "summary": "Use adhesive nasal strips to aid nasal airflow and reduce snoring.",
    "goal_type": "bool",
    "default_target": null,
    "min_viable": "Try one strip for a single night.",
    "time_windows": [{ "start": "20:30", "end": "23:59" }],
    "suggested_rules": [{ "type": "weekly", "params": { "days_per_week": 3 } }],
    "cues_and_stacking": "Store near your nightstand.",
    "equipment": "nasal strips",
    "contraindications": "Skin sensitivity or nasal irritation; discontinue if uncomfortable.",
    "difficulty": "easy",
    "estimated_minutes": 1,
    "coach_copy": null,
    "tags": "breathing,snoring,sleep,nasal",
    "sources": "User-provided PDF: Evidence-Based Biohacks"
  },
  {
    "slug": "glycine-3g-bedtime",
    "name": "Glycine (3 g at bedtime)",
    "domain": "nutrition",
    "category": "supplements",
    "summary": "Evening glycine may support sleep onset and subjective sleep quality for some people.",
    "goal_type": "count",
    "default_target": 3.0,
    "min_viable": "Take 1 gram to test tolerance.",
    "time_windows": [{ "start": "20:00", "end": "23:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Mix into warm herbal tea.",
    "equipment": "powder or capsules",
    "contraindications": "Check meds and medical conditions with a clinician.",
    "difficulty": "easy",
    "estimated_minutes": 1,
    "coach_copy": null,
    "tags": "glycine,sleep,amino-acid,relaxation",
    "sources": "User-provided PDF: Evidence-Based Biohacks"
  },
  {
    "slug": "theanine-200mg-pm",
    "name": "L-Theanine (200 mg afternoon/evening)",
    "domain": "nutrition",
    "category": "supplements",
    "summary": "Theanine may promote calm without sedation.",
    "goal_type": "count",
    "default_target": 200.0,
    "min_viable": "Try 100 mg once.",
    "time_windows": [{ "start": "13:00", "end": "19:00" }],
    "suggested_rules": [{ "type": "weekly", "params": { "days_per_week": 5 } }],
    "cues_and_stacking": "Pair with a screen break.",
    "equipment": "capsules/tablets",
    "contraindications": "Check medication interactions with a clinician.",
    "difficulty": "easy",
    "estimated_minutes": 1,
    "coach_copy": null,
    "tags": "theanine,calm,focus,anxiety",
    "sources": "User-provided PDF: Evidence-Based Biohacks"
  },
  {
    "slug": "omega3-epa-dha-1000mg",
    "name": "Omega-3 EPA+DHA (1000 mg)",
    "domain": "nutrition",
    "category": "supplements",
    "summary": "EPA/DHA may support cardiovascular and cognitive health.",
    "goal_type": "count",
    "default_target": 1000.0,
    "min_viable": "Take 500 mg with a meal.",
    "time_windows": [{ "start": "07:00", "end": "20:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Keep near breakfast supplements.",
    "equipment": "softgels or liquid",
    "contraindications": "Bleeding risk or anticoagulants: consult a clinician.",
    "difficulty": "easy",
    "estimated_minutes": 1,
    "coach_copy": null,
    "tags": "omega-3,EPA,DHA,heart,brain",
    "sources": "User-provided PDF: Evidence-Based Biohacks"
  },
  {
    "slug": "vitamin-d3-1000iu",
    "name": "Vitamin D3 (1000 IU)",
    "domain": "nutrition",
    "category": "supplements",
    "summary": "Daily vitamin D to support status, ideally personalized to labs and clinician guidance.",
    "goal_type": "count",
    "default_target": 1000.0,
    "min_viable": "Take 400-800 IU.",
    "time_windows": [{ "start": "07:00", "end": "12:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Bundle with morning routine.",
    "equipment": "softgel or drops",
    "contraindications": "Hypercalcemia, certain meds; dose per clinician and bloodwork.",
    "difficulty": "easy",
    "estimated_minutes": 1,
    "coach_copy": null,
    "tags": "vitamin-d3,bone,immune,sunlight",
    "sources": "User-provided PDF: Evidence-Based Biohacks"
  },
  {
    "slug": "device-night-mode-evening",
    "name": "Use Device Night Mode After Sunset",
    "domain": "recovery",
    "category": "screen-hygiene",
    "summary": "Reduce blue light on screens after sunset via night mode or warmer color temperature.",
    "goal_type": "bool",
    "default_target": null,
    "min_viable": "Enable on one device today.",
    "time_windows": [{ "start": "18:00", "end": "23:30" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Schedule to turn on automatically at sunset.",
    "equipment": "phone/computer settings",
    "contraindications": "None.",
    "difficulty": "easy",
    "estimated_minutes": 1,
    "coach_copy": null,
    "tags": "screen,blue-light,night-shift,bedtime",
    "sources": "User-provided PDF: Evidence-Based Biohacks"
  },
  {
    "slug": "toe-spacers-30",
    "name": "Toe Spacers (30 min)",
    "domain": "recovery",
    "category": "mobility",
    "summary": "Use toe spacers to encourage natural toe splay and foot comfort.",
    "goal_type": "duration",
    "default_target": 30.0,
    "min_viable": "Wear for 10 minutes while relaxing.",
    "time_windows": [{ "start": "18:00", "end": "22:00" }],
    "suggested_rules": [{ "type": "weekly", "params": { "days_per_week": 4 } }],
    "cues_and_stacking": "Use during reading or TV time.",
    "equipment": "toe spacers",
    "contraindications": "Foot pain, neuropathy, or skin breakdown; discontinue if discomfort.",
    "difficulty": "easy",
    "estimated_minutes": 30,
    "coach_copy": null,
    "tags": "feet,toes,mobility,comfort",
    "sources": "User-provided PDF: Evidence-Based Biohacks"
  },
  {
    "slug": "alternate-nostril-5",
    "name": "Alternate Nostril Breathing (5 min)",
    "domain": "recovery",
    "category": "breathwork",
    "summary": "Gentle pranayama pattern that can reduce arousal and improve focus for some.",
    "goal_type": "duration",
    "default_target": 5.0,
    "min_viable": "Do 60 seconds at a comfortable pace.",
    "time_windows": [{ "start": "12:00", "end": "20:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Pair with 20-20-20 eye breaks.",
    "equipment": "",
    "contraindications": "Skip if congested or dizzy.",
    "difficulty": "easy",
    "estimated_minutes": 5,
    "coach_copy": null,
    "tags": "breathing,pranayama,focus,relaxation",
    "sources": "User-provided PDF: Evidence-Based Biohacks"
  }
]
$json$::jsonb;
BEGIN
  PERFORM public.rpc_upsert_habit_templates(v_payload);
END;
$$;