DO $$
DECLARE
  v_payload jsonb := '[
  /* -------------------- NUTRITION (3) -------------------- */
  {
    "slug": "prebiotic-food-1",
    "name": "Eat 1 Prebiotic Food",
    "domain": "nutrition",
    "category": "gut-health",
    "summary": "Feeds beneficial gut bacteria (e.g., onions, garlic, slightly green banana, oats, legumes).",
    "goal_type": "count",
    "default_target": 1.0,
    "min_viable": "Add a few bites of any prebiotic food.",
    "time_windows": [{ "start": "11:00", "end": "20:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Toss onions/beans into lunch or dinner.",
    "equipment": "",
    "contraindications": "Adjust if FODMAP-sensitive; ramp gradually.",
    "difficulty": "easy",
    "estimated_minutes": 3,
    "coach_copy": null,
    "tags": "prebiotic,gut,fiber,legumes,oats,banana",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "slow-eating-15",
    "name": "Eat Slowly (15 min meal)",
    "domain": "nutrition",
    "category": "portion",
    "summary": "Slower eating supports satiety and better portion control.",
    "goal_type": "duration",
    "default_target": 15.0,
    "min_viable": "Take 5 minutes and set fork down between bites.",
    "time_windows": [{ "start": "11:00", "end": "20:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Use a timer; chew fully.",
    "equipment": "",
    "contraindications": "",
    "difficulty": "easy",
    "estimated_minutes": 15,
    "coach_copy": null,
    "tags": "portion,mindful-eating,satiety",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "protein-dinner-25g",
    "name": "Protein at Dinner (25 g)",
    "domain": "nutrition",
    "category": "protein",
    "summary": "Protein-forward evening meal to support recovery and fullness.",
    "goal_type": "count",
    "default_target": 25.0,
    "min_viable": "Hit at least 15 g once.",
    "time_windows": [{ "start": "17:00", "end": "21:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Plan protein first when building dinner.",
    "equipment": "",
    "contraindications": "Adjust per clinician if kidney disease.",
    "difficulty": "easy",
    "estimated_minutes": 5,
    "coach_copy": null,
    "tags": "protein,dinner,satiety,recovery",
    "sources": "Perplexity deep research"
  },

  /* -------------------- EXERCISE (3) -------------------- */
  {
    "slug": "doorway-lat-stretch-2",
    "name": "Doorway Lat Stretch (2 min)",
    "domain": "exercise",
    "category": "mobility",
    "summary": "Opens lats and shoulders to counter desk posture and aid overhead motion.",
    "goal_type": "duration",
    "default_target": 2.0,
    "min_viable": "Hold 30s/side gently.",
    "time_windows": [{ "start": "10:00", "end": "18:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Do at each bathroom break.",
    "equipment": "",
    "contraindications": "Avoid painful end-range or sharp shoulder pain.",
    "difficulty": "easy",
    "estimated_minutes": 2,
    "coach_copy": null,
    "tags": "lats,shoulders,mobility,posture",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "glute-march-60s",
    "name": "Glute March (60s)",
    "domain": "exercise",
    "category": "strength",
    "summary": "Activates hips and trunk; great warm-up or desk reset.",
    "goal_type": "duration",
    "default_target": 1.0,
    "min_viable": "March in place for 30 seconds.",
    "time_windows": [{ "start": "08:00", "end": "18:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Do before walks or workouts.",
    "equipment": "",
    "contraindications": "Hold support if balance-limited.",
    "difficulty": "easy",
    "estimated_minutes": 1,
    "coach_copy": null,
    "tags": "glutes,activation,strength,warm-up",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "heel-to-toe-walk-60s",
    "name": "Heel-to-Toe Walk (60s)",
    "domain": "exercise",
    "category": "balance",
    "summary": "Improves gait control and balance with a simple drill.",
    "goal_type": "duration",
    "default_target": 1.0,
    "min_viable": "Do 30 seconds along a wall for safety.",
    "time_windows": [{ "start": "09:00", "end": "19:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Practice in a hallway after calls.",
    "equipment": "",
    "contraindications": "Use support if dizziness/instability.",
    "difficulty": "easy",
    "estimated_minutes": 1,
    "coach_copy": null,
    "tags": "balance,gait,stability",
    "sources": "Perplexity deep research"
  },

  /* -------------------- RECOVERY (4) -------------------- */
  {
    "slug": "hrv-biofeedback-5",
    "name": "HRV Biofeedback (5 min)",
    "domain": "recovery",
    "category": "breathwork",
    "summary": "Breathe ~6 breaths/min to improve vagal tone and calm the nervous system.",
    "goal_type": "duration",
    "default_target": 5.0,
    "min_viable": "Do 2 minutes with a pacer app.",
    "time_windows": [{ "start": "12:00", "end": "20:00" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Between meetings or pre-bed.",
    "equipment": "phone app (optional)",
    "contraindications": "Stop if lightheaded; breathe comfortably.",
    "difficulty": "easy",
    "estimated_minutes": 5,
    "coach_copy": null,
    "tags": "hrv,breathing,relaxation,stress",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "white-noise-sleep",
    "name": "Use White Noise for Sleep",
    "domain": "recovery",
    "category": "sleep-hygiene",
    "summary": "Masks environmental noise to reduce awakenings and aid sleep continuity.",
    "goal_type": "bool",
    "default_target": null,
    "min_viable": "Run a fan or app at low volume.",
    "time_windows": [{ "start": "20:00", "end": "23:59" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Start with your digital sunset.",
    "equipment": "fan or phone/app",
    "contraindications": "Keep volume moderate to protect hearing.",
    "difficulty": "easy",
    "estimated_minutes": 1,
    "coach_copy": null,
    "tags": "sleep,noise,continuity",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "sleep-earplugs-or-mask",
    "name": "Sleep with Earplugs or Mask",
    "domain": "recovery",
    "category": "sleep-hygiene",
    "summary": "Reduce noise and light to protect sleep quality when the room isn't ideal.",
    "goal_type": "bool",
    "default_target": null,
    "min_viable": "Use either earplugs or an eye mask.",
    "time_windows": [{ "start": "20:30", "end": "23:59" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Keep items on the nightstand.",
    "equipment": "earplugs, eye mask",
    "contraindications": "Check fit/cleanliness to avoid irritation.",
    "difficulty": "easy",
    "estimated_minutes": 1,
    "coach_copy": null,
    "tags": "sleep,noise,light,mask",
    "sources": "Perplexity deep research"
  },
  {
    "slug": "lavender-aromatherapy-5",
    "name": "Lavender Aromatherapy (5 min)",
    "domain": "recovery",
    "category": "relaxation",
    "summary": "Pleasant scent can reduce pre-sleep arousal for some people.",
    "goal_type": "duration",
    "default_target": 5.0,
    "min_viable": "Take 1–2 slow scented breaths.",
    "time_windows": [{ "start": "19:00", "end": "22:30" }],
    "suggested_rules": [{ "type": "daily", "params": {} }],
    "cues_and_stacking": "Use with progressive relaxation.",
    "equipment": "essential oil or sachet",
    "contraindications": "Avoid if scent-sensitive or with certain pets.",
    "difficulty": "easy",
    "estimated_minutes": 5,
    "coach_copy": null,
    "tags": "lavender,aromatherapy,relaxation,sleep",
    "sources": "Perplexity deep research"
  }
  ]'::jsonb;
BEGIN
  PERFORM public.rpc_upsert_habit_templates(v_payload);
END;
$$;